-- Backfill policies for installations that already applied workflow version 2.
INSERT INTO workflow_transitions(workflow_id,from_state,trigger_code,to_state,authority,guard_code,effect_code) VALUES
 ('00000000-0000-0000-0000-000000000202','DISCOVERY_FAILED','RETRY_ANALYZE_PRODUCT_NEED','ANALYSIS_IN_PROGRESS','OPERATOR','NO_ACTIVE_OPERATION','CREATE_ANALYSIS_JOB'),
 ('00000000-0000-0000-0000-000000000202','DISCOVERY_FAILED','RETRY_DEFINE_PRODUCT_REQUIREMENTS','REQUIREMENTS_IN_PROGRESS','OPERATOR','NO_ACTIVE_OPERATION','CREATE_REQUIREMENTS_JOB'),
 ('00000000-0000-0000-0000-000000000202','DISCOVERY_FAILED','RETRY_REVIEW_PRODUCT_COMMITMENT','REVIEW_IN_PROGRESS','OPERATOR','NO_ACTIVE_OPERATION','CREATE_REVIEW_JOB') ON CONFLICT DO NOTHING;

INSERT INTO workflow_global_policies(policy_code,source_workflow_code,source_state,target_workflow_code,target_workflow_version)
VALUES ('ARCHIVE_PROJECT','PROJECT_DISCOVERY','WAITING_FOR_REVIEW_ADJUSTMENT','PROJECT_ARCHIVING',1) ON CONFLICT DO NOTHING;
