import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';

process.env.DATABASE_URL ??= 'postgres://unused:unused@127.0.0.1:1/unused';
process.env.NAAMIVE_ARTIFACT_STORE_URI ??= `file://${process.cwd()}/.baseline-revision-artifacts`;
process.env.NAAMIVE_OPERATOR_ID ??= 'baseline-revision-tester';

if (process.env.DATABASE_URL.includes('unused')) test('baseline revision integration requires DATABASE_URL', { skip: 'set DATABASE_URL' }, () => {});
else {
  const { pool, withTransaction } = await import('./db.js');
  const { loadCatalogSeedPackage, catalogPackageHash, publishTechnologyCatalog } = await import('./catalog-publisher.js');
  const { validateTechnologyCatalogSeedPackage } = await import('./technology-contracts.js');
  const { createTechnologyBaselineDraft } = await import('./baseline-draft.js');
  const { startTechnologyBaselineRevision } = await import('./baseline-revision.js');
  const { submitTechnologyBaseline, decideTechnologyBaseline } = await import('./baseline-gate.js');
  const { runOnce } = await import('./worker.js');
  const { materializeModule } = await import('./phase3.js');

  const publish = async () => { const seed: any = structuredClone(await loadCatalogSeedPackage()), n = Date.now() * 100 + Math.floor(Math.random() * 99); for (const key of ['categories', 'catalogItems', 'profiles', 'profileItems', 'compatibilityRules', 'catalogRevision']) seed[key].catalog_revision = n; seed.catalogRevision.records[0].catalog_revision = n; seed.catalogRevision.records[0].content_hash = catalogPackageHash(await validateTechnologyCatalogSeedPackage(seed)); return publishTechnologyCatalog(seed, 'baseline-revision-tester', randomUUID()); };
  const inventory = async (project: string, catalogRevisionId: string) => { const intake = (await pool.query(`SELECT id FROM intake_revisions WHERE project_id=$1 LIMIT 1`, [project])).rows[0].id, operation = randomUUID(), job = randomUUID(); await pool.query(`INSERT INTO operations(id,project_id,kind,status,idempotency_key,correlation_id,revision_id) VALUES($1,$2,'TECHNOLOGY_INVENTORY','SUCCEEDED',$3,$4,$5)`, [operation, project, `revision-inventory:${operation}`, randomUUID(), intake]); await pool.query(`INSERT INTO jobs(id,operation_id,project_id,revision_id,kind,status,idempotency_key,completed_at) VALUES($1,$2,$3,$4,'START_TECHNOLOGY_INVENTORY','COMPLETED',$5,clock_timestamp())`, [job, operation, project, intake, `revision-inventory-job:${job}`]); await pool.query(`INSERT INTO technology_inventory(id,project_id,project_key,repository_sha,job_id,technology_catalog_revision_id,source_path,detector_code,confidence,value,resolution_result) VALUES($1,$2::uuid,$2,'000',$3,$4,'package.json','TEST',1,'TEST','UNKNOWN_CATALOG_ITEM')`, [randomUUID(), project, job, catalogRevisionId]); };
  const setup = async () => { const catalog: any = await publish(), project = randomUUID(), context = randomUUID(), intake = randomUUID(), profile = (await pool.query(`SELECT profile_id FROM technology_catalog_revision_profiles WHERE revision_id=$1 AND is_active LIMIT 1`, [catalog.revisionId])).rows[0].profile_id; await pool.query(`INSERT INTO projects(id,title,business_owner,submitted_by,repository_path,repository_origin,base_branch,initial_sha,workflow_code,workflow_version,state,draft) VALUES($1,'baseline revision','owner','tester','/tmp','local','main','000','PROJECT_DISCOVERY',3,'TECHNOLOGY_BASELINE_IN_REVIEW','{}')`, [project]); await pool.query(`INSERT INTO intake_revisions(id,project_id,schema_version,payload,structured_sha256,markdown_sha256,artifact_uri,submitted_by) VALUES($1,$2,1,'{}',$3,$4,'file:///tmp/intake','tester')`, [intake, project, 'a'.repeat(64), 'b'.repeat(64)]); await pool.query(`INSERT INTO technology_selection_contexts(id,project_id,project_key,technology_catalog_revision_id,technology_profile_id,hash,status) VALUES($1,$2::uuid,$2,$3,$4,$5,'READY')`, [context, project, catalog.revisionId, profile, 'c'.repeat(64)]); await inventory(project, catalog.revisionId); const draft: any = await withTransaction(client => createTechnologyBaselineDraft(client, project)); return { project, baseline: draft.baselineId, context, first: draft.revisionId, catalog: catalog.revisionId }; };
  const approve = async (project: string, revision: string, key: string) => { const submitted: any = await submitTechnologyBaseline(project, revision, `submit:${key}`); await decideTechnologyBaseline(project, revision, { gate_id: submitted.gate_id, version: 1, decision: 'APPROVED' }, `approve:${key}`); };
  const createSuccessor = async (project: string, predecessor: string, key: string) => { const started: any = await startTechnologyBaselineRevision(project, predecessor, key); await runOnce(project); const context: any = (await pool.query(`SELECT * FROM technology_selection_contexts WHERE project_key=$1 ORDER BY created_at DESC LIMIT 1`, [project])).rows[0]; await inventory(project, context.technology_catalog_revision_id); const draft: any = await withTransaction(client => createTechnologyBaselineDraft(client, project)); return { started, context, draft }; };

  test.after(() => pool.end());
  test('F5-13 preserves terminal lineage, monotonic numbering, evidence, and approved-module coexistence', async () => {
    const f = await setup(); await approve(f.project, f.first, f.project);
    const first: any = (await pool.query(`SELECT * FROM technology_baseline_revisions WHERE id=$1`, [f.first])).rows[0], second = randomUUID();
    await pool.query(`INSERT INTO technology_baseline_revisions(id,baseline_id,project_id,project_key,technology_catalog_revision_id,selection_context_id,revision_number,status,payload,schema_version) VALUES($1,$2,$3::uuid,$3,$4,$5,2,'APPROVED',$6,'technology-baseline/v1')`, [second, f.baseline, f.project, first.technology_catalog_revision_id, first.selection_context_id, first.payload]);
    const successor = await createSuccessor(f.project, f.first, `start:${f.project}`); const again: any = await startTechnologyBaselineRevision(f.project, f.first, `start:${f.project}`); assert.equal(again.operation_id, successor.started.operation_id);
    const row: any = (await pool.query(`SELECT * FROM technology_baseline_revisions WHERE id=$1`, [successor.draft.revisionId])).rows[0];
    assert.equal(Number(row.revision_number), 3); assert.equal(row.supersedes_revision_id, f.first); assert.equal(row.baseline_id, f.baseline); assert.equal((await pool.query(`SELECT status FROM technology_baseline_revisions WHERE id=$1`, [f.first])).rows[0].status, 'APPROVED'); assert.equal(successor.context.supersedes_baseline_revision_id, f.first); assert.equal((await pool.query(`SELECT status FROM technology_selection_contexts WHERE id=$1`, [f.context])).rows[0].status, 'SUPERSEDED'); assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM artifacts WHERE project_id=$1 AND artifact_type='technology-baseline-revision'`, [f.project])).rows[0].n), 1);
    const latest: any = await materializeModule(f.project, { module_key: `latest-${Date.now()}` }, `latest:${f.project}`), explicit: any = await materializeModule(f.project, { module_key: `explicit-${Date.now()}`, technology_baseline_revision_id: f.first }, `explicit:${f.project}`); assert.equal((await pool.query(`SELECT technology_baseline_revision_id FROM module_revisions WHERE id=$1`, [latest.revision_id])).rows[0].technology_baseline_revision_id, second); assert.equal((await pool.query(`SELECT technology_baseline_revision_id FROM module_revisions WHERE id=$1`, [explicit.revision_id])).rows[0].technology_baseline_revision_id, f.first); const blocked = [{ id: row.id, status: 'DRAFT', number: 3, key: 'draft' }, { id: randomUUID(), status: 'PENDING_APPROVAL', number: 4, key: 'pending' }, { id: randomUUID(), status: 'REJECTED', number: 5, key: 'rejected' }]; for (const entry of blocked) { if (entry.id !== row.id) await pool.query(`INSERT INTO technology_baseline_revisions(id,baseline_id,project_id,project_key,technology_catalog_revision_id,selection_context_id,revision_number,status,payload,schema_version) VALUES($1,$2,$3::uuid,$3,$4,$5,$6,$7,$8,'technology-baseline/v1')`, [entry.id, f.baseline, f.project, first.technology_catalog_revision_id, first.selection_context_id, entry.number, entry.status, first.payload]); await assert.rejects(() => materializeModule(f.project, { module_key: `${entry.key}-${Date.now()}`, technology_baseline_revision_id: entry.id }, `${entry.status}:${f.project}`), /TECHNOLOGY_BASELINE_REVISION_NOT_APPROVED/); }
  });
  test('F5-13 accepts rejected predecessors and rejects non-terminal or active predecessors', async () => { const rejected = await setup(), submitted: any = await submitTechnologyBaseline(rejected.project, rejected.first, `submit:${rejected.project}`); await decideTechnologyBaseline(rejected.project, rejected.first, { gate_id: submitted.gate_id, version: 1, decision: 'REJECTED', feedback: 'adjust' }, `reject:${rejected.project}`); const restarted: any = await startTechnologyBaselineRevision(rejected.project, rejected.first, `rejected:${rejected.project}`); await runOnce(rejected.project); assert.ok(restarted.job_id); const blocked = await setup(); await approve(blocked.project, blocked.first, blocked.project); const active = randomUUID(), initial: any = (await pool.query(`SELECT * FROM technology_baseline_revisions WHERE id=$1`, [blocked.first])).rows[0]; await pool.query(`INSERT INTO technology_baseline_revisions(id,baseline_id,project_id,project_key,technology_catalog_revision_id,selection_context_id,revision_number,status,payload,schema_version) VALUES($1,$2,$3::uuid,$3,$4,$5,2,'DRAFT',$6,'technology-baseline/v1')`, [active, blocked.baseline, blocked.project, initial.technology_catalog_revision_id, initial.selection_context_id, initial.payload]); await assert.rejects(() => startTechnologyBaselineRevision(blocked.project, blocked.first, `active:${blocked.project}`), /TECHNOLOGY_BASELINE_REVISION_ACTIVE_EXISTS/); await assert.rejects(() => startTechnologyBaselineRevision(blocked.project, active, `nonterminal:${blocked.project}`), /TECHNOLOGY_BASELINE_REVISION_NOT_TERMINAL/); });
}
