import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';

process.env.DATABASE_URL ??= 'postgres://unused:unused@127.0.0.1:1/unused';
process.env.NAAMIVE_ARTIFACT_STORE_URI ??= `file://${process.cwd()}/.baseline-gate-artifacts`;
process.env.NAAMIVE_OPERATOR_ID ??= 'baseline-gate-tester';

if (process.env.DATABASE_URL.includes('unused')) test('baseline gate integration requires DATABASE_URL', { skip: 'set DATABASE_URL' }, () => {});
else {
  const { pool, withTransaction } = await import('./db.js');
  const { loadCatalogSeedPackage, catalogPackageHash, publishTechnologyCatalog } = await import('./catalog-publisher.js');
  const { validateTechnologyCatalogSeedPackage } = await import('./technology-contracts.js');
  const { createTechnologyBaselineDraft } = await import('./baseline-draft.js');
  const { decideTechnologyBaseline, submitTechnologyBaseline } = await import('./baseline-gate.js');
  const publish = async () => { const seed: any = structuredClone(await loadCatalogSeedPackage()); const n = Date.now() * 100 + Math.floor(Math.random() * 99); for (const k of ['categories','catalogItems','profiles','profileItems','compatibilityRules','catalogRevision']) seed[k].catalog_revision = n; seed.catalogRevision.records[0].catalog_revision = n; seed.catalogRevision.records[0].content_hash = catalogPackageHash(await validateTechnologyCatalogSeedPackage(seed)); return publishTechnologyCatalog(seed, 'baseline-gate-tester', randomUUID()); };
  const setup = async () => { const catalog: any = await publish(), project = randomUUID(), context = randomUUID(), intake = randomUUID(), operation = randomUUID(), job = randomUUID(); const profile = (await pool.query(`SELECT profile_id FROM technology_catalog_revision_profiles WHERE revision_id=$1 AND is_active LIMIT 1`, [catalog.revisionId])).rows[0].profile_id;
    await pool.query(`INSERT INTO projects(id,title,business_owner,submitted_by,repository_path,repository_origin,base_branch,initial_sha,workflow_code,workflow_version,state,draft) VALUES($1,'gate','owner','tester','/tmp','local','main','000','PROJECT_DISCOVERY',3,'TECHNOLOGY_BASELINE_IN_REVIEW','{}')`, [project]);
    await pool.query(`INSERT INTO intake_revisions(id,project_id,schema_version,payload,structured_sha256,markdown_sha256,artifact_uri,submitted_by) VALUES($1,$2,1,'{}',$3,$4,'file:///tmp/intake','tester')`, [intake,project,'a'.repeat(64),'b'.repeat(64)]);
    await pool.query(`INSERT INTO technology_selection_contexts(id,project_id,project_key,technology_catalog_revision_id,technology_profile_id,hash,status) VALUES($1,$2::uuid,$2,$3,$4,$5,'READY')`, [context,project,catalog.revisionId,profile,'c'.repeat(64)]);
    await pool.query(`INSERT INTO operations(id,project_id,kind,status,idempotency_key,correlation_id,revision_id) VALUES($1,$2,'TECHNOLOGY_INVENTORY','SUCCEEDED',$3,$4,$5)`, [operation,project,`inventory:${project}`,randomUUID(),intake]);
    await pool.query(`INSERT INTO jobs(id,operation_id,project_id,revision_id,kind,status,idempotency_key,completed_at) VALUES($1,$2,$3,$4,'START_TECHNOLOGY_INVENTORY','COMPLETED',$5,clock_timestamp())`, [job,operation,project,intake,`job:${project}`]);
    await pool.query(`INSERT INTO technology_inventory(id,project_id,project_key,repository_sha,job_id,technology_catalog_revision_id,source_path,detector_code,confidence,value,resolution_result) VALUES($1,$2::uuid,$2,'000',$3,$4,'package.json','TEST',1,'TEST','UNKNOWN_CATALOG_ITEM')`, [randomUUID(),project,job,catalog.revisionId]);
    const draft: any = await withTransaction(c => createTechnologyBaselineDraft(c, project)); return { project, revision: draft.revisionId };
  };
  test.after(() => pool.end());
  test('submits exactly one valid DRAFT gate, transitions the project, records event, and is idempotent', async () => { const f = await setup(), key = `submit:${f.project}`; const first: any = await submitTechnologyBaseline(f.project, f.revision, key); const second: any = await submitTechnologyBaseline(f.project, f.revision, key); assert.equal(first.operation_id, second.operation_id); const gate: any = (await pool.query('SELECT * FROM technology_baseline_gates WHERE baseline_revision_id=$1',[f.revision])).rows[0]; assert.equal(gate.status,'OPEN'); assert.equal(Number((await pool.query('SELECT count(*)::int n FROM technology_baseline_gates WHERE baseline_revision_id=$1',[f.revision])).rows[0].n),1); assert.equal((await pool.query('SELECT status FROM technology_baseline_revisions WHERE id=$1',[f.revision])).rows[0].status,'PENDING_APPROVAL'); assert.equal((await pool.query('SELECT state FROM projects WHERE id=$1',[f.project])).rows[0].state,'WAITING_FOR_TECHNOLOGY_BASELINE'); assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM events WHERE project_id=$1 AND event_type='TECHNOLOGY_BASELINE_SUBMITTED'`,[f.project])).rows[0].n),1); });
  test('fails closed for invalid project, missing/non-DRAFT revision, and invalid frozen snapshot', async () => { const f = await setup(); await assert.rejects(() => submitTechnologyBaseline(f.project, randomUUID(), 'missing'), /TECHNOLOGY_BASELINE_REVISION_NOT_FOUND/); await pool.query(`UPDATE projects SET state='PRODUCT_COMMITMENT' WHERE id=$1`,[f.project]); await assert.rejects(() => submitTechnologyBaseline(f.project,f.revision,'bad-project'),/WORKFLOW_TRANSITION_NOT_ALLOWED/); await pool.query(`UPDATE projects SET state='TECHNOLOGY_BASELINE_IN_REVIEW' WHERE id=$1`,[f.project]); await pool.query(`UPDATE technology_baseline_revisions SET status='REJECTED' WHERE id=$1`,[f.revision]); await assert.rejects(() => submitTechnologyBaseline(f.project,f.revision,'not-draft'),/TECHNOLOGY_BASELINE_REVISION_NOT_DRAFT/); });
  test('approves and rejects versioned gates with immutable evidence and idempotency', async () => { const approved = await setup(); const rejected = await setup(); const a: any = await submitTechnologyBaseline(approved.project,approved.revision,`submit:${approved.project}`); const gateA: any = (await pool.query('SELECT * FROM technology_baseline_gates WHERE id=$1',[a.gate_id])).rows[0]; await assert.rejects(() => decideTechnologyBaseline(approved.project,approved.revision,{gate_id:gateA.id,version:2,decision:'APPROVED'},`wrong:${approved.project}`),/GATE_VERSION_CONFLICT/); const decision: any = await decideTechnologyBaseline(approved.project,approved.revision,{gate_id:gateA.id,version:1,decision:'APPROVED'},`decision:${approved.project}`); assert.equal((await decideTechnologyBaseline(approved.project,approved.revision,{gate_id:gateA.id,version:1,decision:'APPROVED'},`decision:${approved.project}`) as any).operation_id,decision.operation_id); const stored: any = (await pool.query('SELECT * FROM technology_baseline_gates WHERE id=$1',[gateA.id])).rows[0]; assert.equal(stored.status,'APPROVED'); assert.match(stored.revision_hash,/^[a-f0-9]{64}$/); assert.match(stored.decision_artifact_hash,/^[a-f0-9]{64}$/); assert.equal((await pool.query('SELECT status FROM technology_baseline_revisions WHERE id=$1',[approved.revision])).rows[0].status,'APPROVED'); assert.equal((await pool.query('SELECT state FROM projects WHERE id=$1',[approved.project])).rows[0].state,'READY_FOR_MODULE_MATERIALIZATION'); const artifact: any = (await pool.query(`SELECT storage_uri FROM artifacts WHERE project_id=$1 AND artifact_type='technology-baseline-decision'`,[approved.project])).rows[0]; assert.equal(JSON.parse(readFileSync(new URL(artifact.storage_uri),'utf8')).revision_hash,stored.revision_hash);
    const r: any = await submitTechnologyBaseline(rejected.project,rejected.revision,`submit:${rejected.project}`); const gateR: any = (await pool.query('SELECT * FROM technology_baseline_gates WHERE id=$1',[r.gate_id])).rows[0]; await assert.rejects(() => decideTechnologyBaseline(rejected.project,rejected.revision,{gate_id:gateR.id,version:1,decision:'REJECTED'},`no-feedback:${rejected.project}`),/GATE_FEEDBACK_REQUIRED/); await decideTechnologyBaseline(rejected.project,rejected.revision,{gate_id:gateR.id,version:1,decision:'REJECTED',feedback:'adjust'},`decision:${rejected.project}`); assert.equal((await pool.query('SELECT status FROM technology_baseline_gates WHERE id=$1',[gateR.id])).rows[0].status,'REJECTED'); assert.equal((await pool.query('SELECT status FROM technology_baseline_revisions WHERE id=$1',[rejected.revision])).rows[0].status,'REJECTED'); assert.equal((await pool.query('SELECT state FROM projects WHERE id=$1',[rejected.project])).rows[0].state,'TECHNOLOGY_BASELINE_IN_REVIEW'); });
}
