/**
 * LIFECYCLE_CONFORMANCE:v1 is the auditable index for the transversal
 * lifecycle certification.  It deliberately points at independently useful
 * tests instead of hiding the contract in one aggregate test.
 */
export const LIFECYCLE_CONFORMANCE_VERSION = 'LIFECYCLE_CONFORMANCE:v1' as const;

export type LifecycleConformanceCriterion = {
  id: number;
  scenario: string;
  layers: readonly string[];
  evidence: readonly string[];
  proofType: readonly ('STATIC' | 'POSTGRES_E2E' | 'HTTP' | 'SSE' | 'BROWSER' | 'GIT')[];
  requiresPostgres: boolean;
  negativeAssertions: readonly string[];
  expectedEvidence: readonly string[];
};

const runtime = 'naamive/runtime/node-web/src/';
const task = 'naamive/orchestration/demand-intake/node-web-orchestration-platform/phase-6-5-implementation-tasks/';

export const LIFECYCLE_CONFORMANCE_CRITERIA: readonly LifecycleConformanceCriterion[] = [
  { id: 1, scenario: 'v2 work item has no individual authorization', layers: ['workflow', 'scheduler', 'UI'], evidence: [runtime+'lifecycle-conformance-audit-scenario.e2e.test.ts', runtime+'workflow-selection.e2e.test.ts', runtime+'ui-01-focused.e2e.test.ts'], proofType: ['POSTGRES_E2E', 'BROWSER'], requiresPostgres: true, negativeAssertions: ['v2 never enters WAITING_FOR_WORK_ITEM_AUTHORIZATION', 'v2 publishes no AUTHORIZE_WORK_ITEM action'], expectedEvidence: ['workflow/version', 'projection allowed_actions'] },
  { id: 2, scenario: 'eligible roots and dependents dispatch once', layers: ['scheduler', 'persistence'], evidence: [runtime+'eligibility-scheduler.e2e.test.ts', runtime+'lifecycle-conformance-audit-scenario.e2e.test.ts'], proofType: ['POSTGRES_E2E'], requiresPostgres: true, negativeAssertions: ['replay creates no second delivery or job'], expectedEvidence: ['scheduling decision', 'delivery/job cardinality'] },
  { id: 3, scenario: 'integration re-evaluates technical dependencies', layers: ['AUT-02', 'scheduler'], evidence: [runtime+'automatic-assurance-integration.e2e.test.ts', runtime+'eligibility-scheduler.e2e.test.ts'], proofType: ['POSTGRES_E2E', 'GIT'], requiresPostgres: true, negativeAssertions: ['execution, QA and ACCEPT without integration do not release a dependent'], expectedEvidence: ['integration lineage', 'dependency decision'] },
  { id: 4, scenario: 'production automatically starts QA and independent review', layers: ['worker', 'assurance'], evidence: [runtime+'automatic-assurance-qa.e2e.test.ts', runtime+'automatic-assurance-integration.e2e.test.ts'], proofType: ['POSTGRES_E2E'], requiresPostgres: true, negativeAssertions: ['no human QA, review or merge command is required'], expectedEvidence: ['candidate', 'QA report', 'review'] },
  { id: 5, scenario: 'only ACCEPT completes assurance work', layers: ['execution', 'assurance'], evidence: [runtime+'automatic-assurance-qa.e2e.test.ts', runtime+'assurance-acceptance-replay.e2e.test.ts'], proofType: ['POSTGRES_E2E'], requiresPostgres: true, negativeAssertions: ['execution success and QA PASS are not ACCEPT'], expectedEvidence: ['acceptance', 'review decision'] },
  { id: 6, scenario: 'rework is automatic unless material authority is required', layers: ['assurance', 'recovery'], evidence: [runtime+'automatic-assurance-qa.e2e.test.ts', runtime+'recovery.e2e.test.ts'], proofType: ['POSTGRES_E2E'], requiresPostgres: true, negativeAssertions: ['stale generation cannot be accepted or started'], expectedEvidence: ['finding', 'rework lineage'] },
  { id: 7, scenario: 'block routes or assists before escalation', layers: ['REC-02', 'gates', 'UI'], evidence: [runtime+'reviewer-recovery-identity.e2e.test.ts', runtime+'reviewer-recovery-cancellation.e2e.test.ts', runtime+'ui-02-stop-surfaces.test.ts'], proofType: ['POSTGRES_E2E', 'BROWSER'], requiresPostgres: true, negativeAssertions: ['no premature human escalation'], expectedEvidence: ['block', 'routing intent', 'stop surface'] },
  { id: 8, scenario: 'recoverable failures retain visible retry/restart lineage', layers: ['REC-01', 'AUT-02 recovery', 'worker', 'UI'], evidence: [runtime+'recovery.e2e.test.ts', runtime+'aut02-integration-recovery.e2e.test.ts', runtime+'worker-restart.e2e.test.ts', runtime+'ui-01-focused.e2e.test.ts'], proofType: ['POSTGRES_E2E', 'GIT'], requiresPostgres: true, negativeAssertions: ['confirmed effect is not blindly replayed', 'unknown AUT-02 pipeline version fails closed'], expectedEvidence: ['recovery decision', 'attempt lineage', 'candidate/member finalization'] },
  { id: 9, scenario: 'every recoverable stop has a fail-closed mapper', layers: ['recovery', 'projection'], evidence: [runtime+'recovery-policy.test.ts', runtime+'ui-02-stop-surfaces.test.ts'], proofType: ['STATIC', 'POSTGRES_E2E'], requiresPostgres: true, negativeAssertions: ['unmapped state fails closed'], expectedEvidence: ['recovery action', 'stop surface'] },
  { id: 10, scenario: 'only proportional published gates are opened', layers: ['workflow', 'gate catalog'], evidence: [runtime+'gate-catalog.e2e.test.ts', runtime+'workflow-selection.e2e.test.ts'], proofType: ['POSTGRES_E2E'], requiresPostgres: true, negativeAssertions: ['no technical or per-work-item human gate'], expectedEvidence: ['gate record', 'transition audit'] },
  { id: 11, scenario: 'human stops expose authority and consequences', layers: ['projection', 'browser'], evidence: [runtime+'ui-01-focused.e2e.test.ts', runtime+'ui-02-stop-surfaces.test.ts'], proofType: ['POSTGRES_E2E', 'BROWSER'], requiresPostgres: true, negativeAssertions: ['incomplete descriptor cannot create a form', 'legacy is not an ordinary human stop'], expectedEvidence: ['sanitized JSON', 'DOM'] },
  { id: 12, scenario: 'ACCEPT automatically drives merge, candidate, validation and integration', layers: ['AUT-02', 'Git'], evidence: [runtime+'automatic-assurance-integration.e2e.test.ts', runtime+'lifecycle-conformance-audit-scenario.e2e.test.ts'], proofType: ['POSTGRES_E2E', 'GIT'], requiresPostgres: true, negativeAssertions: ['no click is required and replay does not duplicate effects'], expectedEvidence: ['SHA', 'manifest', 'intents'] },
  { id: 13, scenario: 'macro lifecycle follows integrated work', layers: ['macro lifecycle', 'workflow'], evidence: [runtime+'macro-lifecycle.test.ts', runtime+'delivery-lifecycle.test.ts'], proofType: ['POSTGRES_E2E'], requiresPostgres: true, negativeAssertions: ['a child does not overtake its parent'], expectedEvidence: ['macro intent', 'macro state'] },
  { id: 14, scenario: 'authenticated final delivery acceptance reaches DELIVERED', layers: ['delivery', 'RBAC'], evidence: [runtime+'delivery-final-gaps.e2e.test.ts', runtime+'delivery-http-rbac.e2e.test.ts'], proofType: ['POSTGRES_E2E', 'HTTP'], requiresPostgres: true, negativeAssertions: ['service, header, payload or stale package cannot deliver'], expectedEvidence: ['package hash', 'gate audit', 'state'] },
  { id: 15, scenario: 'pause and cancellation remain distinct from archive', layers: ['workflow', 'delivery', 'UI'], evidence: [runtime+'delivery-pause-cancellation.e2e.test.ts', runtime+'ui-01-focused.e2e.test.ts'], proofType: ['POSTGRES_E2E'], requiresPostgres: true, negativeAssertions: ['pause does not cancel and cancellation preserves evidence'], expectedEvidence: ['pause/resume/cancellation records'] },
  { id: 16, scenario: 'sensitive actions require authenticated scoped authority', layers: ['auth', 'HTTP'], evidence: [runtime+'auth.e2e.test.ts', runtime+'delivery-http-rbac.e2e.test.ts'], proofType: ['POSTGRES_E2E', 'HTTP'], requiresPostgres: true, negativeAssertions: ['header or payload grants no role', 'service principal cannot make a human decision'], expectedEvidence: ['session audit', '401/403'] },
  { id: 17, scenario: 'API, SSE and browser consume one server projection', layers: ['API', 'SSE', 'browser'], evidence: [runtime+'ui-01-focused.e2e.test.ts', runtime+'module-plan-review-sse.e2e.test.ts', runtime+'web-ui-f6-12.e2e.test.ts'], proofType: ['POSTGRES_E2E', 'SSE', 'BROWSER'], requiresPostgres: true, negativeAssertions: ['client invents no capability and stale SSE cannot regress an action'], expectedEvidence: ['as_of_event_id', 'JSON', 'DOM'] },
  { id: 18, scenario: 'Persistence → Metric → Interface audited journey', layers: ['all'], evidence: [runtime+'lifecycle-conformance-audit-scenario.e2e.test.ts'], proofType: ['POSTGRES_E2E', 'GIT'], requiresPostgres: true, negativeAssertions: ['Metric cannot dispatch before accepted and integrated Persistence', 'Interface cannot dispatch before dependency and priority-group blocker are resolved', 'no dependent scheduleWorkItem call exists in the fixture'], expectedEvidence: ['sanitized scenario report', 'IDs', 'hashes', 'teardown'] },
  { id: 19, scenario: 'crash, concurrency and replay preserve cardinality', layers: ['scheduler', 'recovery', 'AUT-02 recovery', 'assurance'], evidence: [runtime+'eligibility-scheduler.e2e.test.ts', runtime+'recovery.e2e.test.ts', runtime+'aut02-integration-recovery.e2e.test.ts', runtime+'worker-restart.e2e.test.ts', runtime+'assurance-acceptance-replay.e2e.test.ts'], proofType: ['POSTGRES_E2E', 'GIT'], requiresPostgres: true, negativeAssertions: ['retry, replay and restart do not duplicate delivery, review, candidate, merge or integration', 'AUT-02 recovery must use collective finalization for v1 and v2'], expectedEvidence: ['cardinality', 'lineage', 'candidate/member/reservation state'] },
  { id: 20, scenario: 'normative documentation, published workflows and runtime agree', layers: ['docs', 'migration', 'runtime'], evidence: [runtime+'lifecycle-conformance.test.ts', 'naamive/runtime/node-web/migrations/048_phase_6_5_conformant_workflows.sql', 'naamive/orchestration/LIFECYCLE_COMPASS.md', 'naamive/orchestration/ORCHESTRATION_PROTOCOL.md', 'naamive/governance/GATE_POLICY.md', task+'TST-01-lifecycle-conformance-suite.md'], proofType: ['STATIC'], requiresPostgres: false, negativeAssertions: ['unknown references fail closed', 'v2 cannot regain individual authorization', 'ACCEPT cannot mean execution success', 'removed gate cannot reappear as current'], expectedEvidence: ['link/version report'] },
] as const;
