import { randomUUID, createHash } from 'node:crypto';
import { pool, withTransaction } from './db.js';
import { config } from './config.js';
import { putArtifact } from './artifacts.js';
import { ApiError } from './service.js';

const event=(c:any,p:string,t:string,correlation:string,payload:object)=>c.query(`INSERT INTO events(project_id,event_type,correlation_id,payload,actor_id) VALUES($1,$2,$3,$4,$5)`,[p,t,correlation,payload,config().operatorId]);
const key=(v:unknown)=>typeof v==='string'&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v);
const idem=async(c:any,k:string)=>{const r=await c.query(`SELECT id FROM operations WHERE idempotency_key=$1`,[k]);return r.rows[0]?.id as string|undefined};
const operation=async(c:any,p:string,kind:string,k:string,correlation:string)=>{const id=randomUUID();await c.query(`INSERT INTO operations(id,project_id,kind,status,idempotency_key,correlation_id) VALUES($1,$2,$3,'SUCCEEDED',$4,$5)`,[id,p,kind,k,correlation]);return id};

export const materializeModule=async(projectId:string,body:Record<string,unknown>,idempotencyKey:string)=>withTransaction(async c=>{const existing=await idem(c,idempotencyKey);if(existing)return{operation_id:existing,status:'ACCEPTED'};const moduleKey=body.module_key;if(!key(moduleKey))throw new ApiError(422,'MODULE_KEY_INVALID');const p=await c.query(`SELECT state FROM projects WHERE id=$1 FOR UPDATE`,[projectId]);if(!p.rowCount)throw new ApiError(404,'PROJECT_NOT_FOUND');if(p.rows[0].state!=='PRODUCT_COMMITMENT')throw new ApiError(409,'WORKFLOW_TRANSITION_NOT_ALLOWED');const rev=randomUUID(),moduleId=randomUUID(),round=randomUUID(),correlation=randomUUID(),op=await operation(c,projectId,'MATERIALIZE_MODULE',idempotencyKey,correlation);const payload={schema_version:1,module_key:moduleKey,name:body.name,objective:body.objective,scope:body.scope,out_of_scope:body.out_of_scope,dependencies:body.dependencies,acceptance_criteria:body.acceptance_criteria,source_gate:body.source_gate};await c.query(`INSERT INTO module_revisions(id,project_id,module_key,revision,payload,status) VALUES($1,$2,$3,1,$4,'PENDING_APPROVAL')`,[rev,projectId,moduleKey,payload]);await c.query(`INSERT INTO modules(id,project_id,module_key,current_revision_id) VALUES($1,$2,$3,$4)`,[moduleId,projectId,moduleKey,rev]);await c.query(`INSERT INTO module_rounds(id,module_id,revision_id,round_number,state) VALUES($1,$2,$3,1,'WAITING_FOR_MODULE_APPROVAL')`,[round,moduleId,rev]);await putArtifact(c,projectId,'module-definition',JSON.stringify({...payload,correlation_id:correlation}),op);await event(c,projectId,'MODULE_MATERIALIZED',correlation,{module_id:moduleId,module_key:moduleKey,revision_id:rev});return{operation_id:op,status:'ACCEPTED',module_id:moduleId,revision_id:rev};});

export const decideModule=async(projectId:string,moduleId:string,body:Record<string,unknown>,idempotencyKey:string)=>withTransaction(async c=>{const existing=await idem(c,idempotencyKey);if(existing)return{operation_id:existing,status:'ACCEPTED'};const m=await c.query(`SELECT m.*,r.id revision_id FROM modules m JOIN module_revisions r ON r.id=m.current_revision_id WHERE m.id=$1 AND m.project_id=$2 FOR UPDATE`,[moduleId,projectId]);if(!m.rowCount)throw new ApiError(404,'MODULE_NOT_FOUND');const approved=body.decision==='APPROVED',feedback=typeof body.feedback==='string'?body.feedback.trim():'';if(!approved&&!feedback)throw new ApiError(422,'GATE_FEEDBACK_REQUIRED');const correlation=randomUUID(),op=await operation(c,projectId,'DECIDE_MODULE',idempotencyKey,correlation);if(approved){await c.query(`UPDATE module_revisions SET status='APPROVED',approved_gate_id=$2 WHERE id=$1`,[m.rows[0].revision_id,randomUUID()]);await c.query(`UPDATE modules SET state='DEFINITION_IN_PROGRESS',version=version+1 WHERE id=$1`,[moduleId]);}await event(c,projectId,approved?'MODULE_APPROVED':'MODULE_REJECTED',correlation,{module_id:moduleId,feedback});return{operation_id:op,status:'ACCEPTED'};});

export const authorizeWorkItem=async(projectId:string,moduleId:string,body:Record<string,unknown>,idempotencyKey:string)=>withTransaction(async c=>{const existing=await idem(c,idempotencyKey);if(existing)return{operation_id:existing,status:'ACCEPTED'};const m=await c.query(`SELECT * FROM modules WHERE id=$1 AND project_id=$2 FOR UPDATE`,[moduleId,projectId]);if(!m.rowCount)throw new ApiError(404,'MODULE_NOT_FOUND');if(!['PLANNING_IN_PROGRESS','WORK_ITEMS_ACTIVE','DEFINITION_IN_PROGRESS'].includes(m.rows[0].state))throw new ApiError(409,'WORKFLOW_TRANSITION_NOT_ALLOWED');const title=typeof body.title==='string'?body.title.trim():'';if(!title||!Array.isArray(body.allowlist)||!Array.isArray(body.qa_matrix))throw new ApiError(422,'WORK_ITEM_CONTRACT_INVALID');const round=(await c.query(`SELECT id FROM module_rounds WHERE module_id=$1 ORDER BY round_number DESC LIMIT 1`,[moduleId])).rows[0];const id=randomUUID(),correlation=randomUUID(),op=await operation(c,projectId,'AUTHORIZE_WORK_ITEM',idempotencyKey,correlation);const payload={schema_version:1,inputs:body.inputs??[],allowlist:body.allowlist,denylist:body.denylist??[],output:body.output,acceptance_criteria:body.acceptance_criteria??[],qa_matrix:body.qa_matrix};await c.query(`INSERT INTO work_items(id,project_id,module_id,revision_id,round_id,title,payload) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,projectId,moduleId,m.rows[0].current_revision_id,round.id,title,payload]);await c.query(`UPDATE modules SET state='WORK_ITEMS_ACTIVE',version=version+1 WHERE id=$1`,[moduleId]);await putArtifact(c,projectId,'module-plan',JSON.stringify({work_item_id:id,...payload,correlation_id:correlation}),op);await event(c,projectId,'WORK_ITEM_AUTHORIZED',correlation,{work_item_id:id,module_id:moduleId});return{operation_id:op,status:'ACCEPTED',work_item_id:id};});

export const phase3Detail=async(projectId:string)=>({modules:(await pool.query(`SELECT m.*,r.payload revision FROM modules m JOIN module_revisions r ON r.id=m.current_revision_id WHERE m.project_id=$1 ORDER BY m.created_at`,[projectId])).rows,work_items:(await pool.query(`SELECT * FROM work_items WHERE project_id=$1 ORDER BY created_at`,[projectId])).rows,deliveries:(await pool.query(`SELECT * FROM deliveries WHERE project_id=$1 ORDER BY created_at DESC`,[projectId])).rows,findings:(await pool.query(`SELECT * FROM findings WHERE project_id=$1 ORDER BY created_at DESC`,[projectId])).rows,candidates:(await pool.query(`SELECT * FROM integration_candidates WHERE project_id=$1 ORDER BY created_at DESC`,[projectId])).rows});

export const findingFingerprint=(description:string)=>createHash('sha256').update(description.trim().toLowerCase()).digest('hex');
