import { pool } from './db.js';
import { reconcileArtifactIntents } from './artifacts.js';
import { agentExecutionService } from './agent-execution-service.js';
import { reconcileEligibilityScheduler } from './eligibility-scheduler.js';
import { reconcileCauseAwareRecovery } from './recovery.js';
const recovered = await reconcileArtifactIntents();
const recoveredDispatches = await agentExecutionService.recoverDispatchedAttempts();
const recoveredEligibility = await reconcileEligibilityScheduler();
const recoveredRecovery = await reconcileCauseAwareRecovery();
console.log(JSON.stringify({ recovered, recovered_dispatches: recoveredDispatches, recovered_eligibility: recoveredEligibility.length, recovered_recovery: recoveredRecovery }));
await pool.end();
