import { randomUUID } from 'node:crypto';
import { pool, withTransaction } from './db.js';
import { ArtifactStorageError, putArtifact } from './artifacts.js';
import { validateIntake } from './service.js';
import { config } from './config.js';
import { transitionTarget } from './workflow.js';
import { AgentConfigurationError, AgentExecutionError, AgentReadinessError, checkAgentReadiness, executeAgent } from './agent.js';
import { log } from './log.js';
import { prepareDevelopmentJob } from './phase3.js';

const delays=[5,15,30];
const leaseSeconds=()=>Math.max(config().agentTimeoutSeconds+config().agentHeartbeatSeconds*2,120);
const event=async(c:any,p:string,t:string,o:any,j:any,r:any,payload:object={})=>c.query(`INSERT INTO events(project_id,event_type,correlation_id,operation_id,job_id,revision_id,payload,actor_id,workflow_code,workflow_version) SELECT $1,$2,$3,$4,$5,$6,$7,$8,workflow_code,workflow_version FROM projects WHERE id=$1`,[p,t,randomUUID(),o,j,r,payload,config().operatorId]);
const nextJob=async(c:any,job:any,kind:string)=>{const id=randomUUID();await c.query(`INSERT INTO jobs(id,operation_id,project_id,revision_id,kind,idempotency_key) VALUES($1,$2,$3,$4,$5,$6)`,[id,job.operation_id,job.project_id,job.revision_id,kind,`${kind}:${job.operation_id}:${id}`]);return id;};

const leaseJob=(projectId?:string)=>withTransaction(async c=>{const q=await c.query(`WITH x AS (SELECT id FROM jobs WHERE ($2::text IS NULL OR project_id=$2) AND ((status IN ('PENDING','RETRYABLE') AND available_at<=clock_timestamp()) OR(status='LEASED' AND lease_expires_at<clock_timestamp())) ORDER BY available_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE jobs SET status='LEASED',attempts=attempts+1,lease_expires_at=clock_timestamp()+($1||' seconds')::interval,heartbeat_at=clock_timestamp() WHERE id IN(SELECT id FROM x) RETURNING *`,[String(leaseSeconds()),projectId??null]);if(!q.rowCount)return null;const job=q.rows[0];await c.query(`UPDATE operations SET status='RUNNING' WHERE id=$1`,[job.operation_id]);return job;});

const completeJob=async(job:any,result?:any)=>withTransaction(async c=>{
  const owned=await c.query(`SELECT 1 FROM jobs WHERE id=$1 AND status='LEASED' AND lease_expires_at>=clock_timestamp() FOR UPDATE`,[job.id]);if(!owned.rowCount)throw new Error('JOB_LEASE_LOST');
  const rev=job.revision_id?(await c.query('SELECT payload FROM intake_revisions WHERE id=$1',[job.revision_id])).rows[0]:undefined;
  if(job.kind==='DEVELOP_WORK_ITEM') {
    // The worktree has already been created by the leased worker.  The actual
    // delivery remains open for the isolated development agent and QA command.
  } else if(job.kind==='VALIDATE_INTAKE'){
    const errors=validateIntake(rev.payload);await putArtifact(c,job.project_id,'validation-report',JSON.stringify({schema_version:1,result:errors.length?'INVALID':'VALID',errors}),job.id);
    if(errors.length)await event(c,job.project_id,'INTAKE_REQUIRES_ADJUSTMENT',job.operation_id,job.id,job.revision_id,{errors});
    else {const gateId=randomUUID();await putArtifact(c,job.project_id,'gate-opened',JSON.stringify({gate_id:gateId}),job.id,gateId);const target=await transitionTarget(c,job.project_id,'INTAKE_VALIDATED');await c.query('UPDATE projects SET state=$2 WHERE id=$1',[job.project_id,target]);await c.query(`INSERT INTO gates(id,project_id,kind,revision_id) VALUES($1,$2,'REGISTER_PROJECT',$3)`,[gateId,job.project_id,job.revision_id]);await event(c,job.project_id,'INTAKE_VALIDATED',job.operation_id,job.id,job.revision_id);await event(c,job.project_id,'GATE_OPENED',job.operation_id,job.id,job.revision_id,{gate_id:gateId,kind:'REGISTER_PROJECT'});}
  } else {
    const type=job.kind==='ANALYZE_PRODUCT_NEED'?'product-need-analysis':job.kind==='DEFINE_PRODUCT_REQUIREMENTS'?'product-requirements':'product-commitment-review';const artifact=await putArtifact(c,job.project_id,type,JSON.stringify({schema_version:1,correlation_id:job.operation_id,input_references:[],...result.evidence,result:result.result}),job.id);await c.query(`UPDATE artifacts SET metadata=$3 WHERE project_id=$1 AND storage_key=$2`,[job.project_id,artifact.key,result.evidence]);let trigger='',next='';if(job.kind==='ANALYZE_PRODUCT_NEED'){trigger='ANALYSIS_COMPLETED';next='DEFINE_PRODUCT_REQUIREMENTS';}else if(job.kind==='DEFINE_PRODUCT_REQUIREMENTS'){trigger='REQUIREMENTS_COMPLETED';next='REVIEW_PRODUCT_COMMITMENT';}else if(result.result==='REQUIRES_ADJUSTMENT'){trigger='REVIEW_REQUIRES_ADJUSTMENT';}else trigger='REVIEW_READY_FOR_GATE';const target=await transitionTarget(c,job.project_id,trigger);await c.query('UPDATE projects SET state=$2,updated_at=clock_timestamp() WHERE id=$1',[job.project_id,target]);await event(c,job.project_id,trigger,job.operation_id,job.id,job.revision_id,{agent:job.kind,phase:type,evidence_type:type,evidence_hash:artifact.hash,result:result.result,next_action:next||'Aguardando sua decisão'});if(next)await nextJob(c,job,next);else if(trigger==='REVIEW_READY_FOR_GATE'){const candidateGateId=randomUUID();const evidence=(await c.query(`SELECT artifact_type,sha256,metadata FROM (SELECT DISTINCT ON (artifact_type) artifact_type,sha256,metadata,created_at FROM artifacts WHERE project_id=$1 AND artifact_type IN ('product-need-analysis','product-requirements','product-commitment-review') ORDER BY artifact_type,created_at DESC) latest ORDER BY created_at`,[job.project_id])).rows;if(evidence.length!==3)throw new Error('PRODUCT_COMMITMENT_EVIDENCE_INCOMPLETE');const inserted=await c.query(`INSERT INTO gates(id,project_id,kind,revision_id,evidence) VALUES($1,$2,'PRODUCT_COMMITMENT',$3,$4) ON CONFLICT (project_id) WHERE status='OPEN' DO NOTHING RETURNING id`,[candidateGateId,job.project_id,job.revision_id,{evidence}]);const gateId=inserted.rows[0]?.id??(await c.query(`SELECT id FROM gates WHERE project_id=$1 AND status='OPEN' FOR UPDATE`,[job.project_id])).rows[0]?.id;if(!gateId)throw new Error('PRODUCT_COMMITMENT_GATE_NOT_CREATED');await event(c,job.project_id,'GATE_OPENED',job.operation_id,job.id,job.revision_id,{gate_id:gateId,kind:'PRODUCT_COMMITMENT',evidence});}}
  await c.query(`UPDATE jobs SET status='COMPLETED',completed_at=clock_timestamp() WHERE id=$1`,[job.id]);const pending=await c.query(`SELECT 1 FROM jobs WHERE operation_id=$1 AND status IN('PENDING','RETRYABLE','LEASED')`,[job.operation_id]);if(!pending.rowCount)await c.query(`UPDATE operations SET status='SUCCEEDED',completed_at=clock_timestamp() WHERE id=$1`,[job.operation_id]);
});

const failJob=async(job:any,error:unknown)=>withTransaction(async c=>{const code=error instanceof AgentConfigurationError||error instanceof AgentExecutionError||error instanceof AgentReadinessError||error instanceof ArtifactStorageError?error.code:'AGENT_EXECUTION_FAILED';const current=(await c.query(`SELECT attempts FROM jobs WHERE id=$1 AND status='LEASED' FOR UPDATE`,[job.id])).rows[0];if(!current)return;const permanent=Number(current.attempts)>config().agentMaxRetries,delay=delays[Math.min(Number(current.attempts)-1,2)];await c.query(`UPDATE jobs SET status=$2,last_error=$3,available_at=clock_timestamp()+($4||' seconds')::interval,completed_at=CASE WHEN $2='FAILED' THEN clock_timestamp() END WHERE id=$1`,[job.id,permanent?'FAILED':'RETRYABLE',code,String(delay)]);if(permanent){await c.query(`UPDATE operations SET status='FAILED',failure_code=$2,completed_at=clock_timestamp() WHERE id=$1`,[job.operation_id,code]);if(job.kind!=='VALIDATE_INTAKE'){const target=await transitionTarget(c,job.project_id,'AGENT_EXECUTION_FAILED');await c.query(`UPDATE projects SET state=$2,failure_stage=$3,failure_code=$4,updated_at=clock_timestamp() WHERE id=$1`,[job.project_id,target,job.kind,code]);}await event(c,job.project_id,'AGENT_EXECUTION_FAILED',job.operation_id,job.id,job.revision_id,{code,stage:job.kind,next_action:'Corrija o problema e tente novamente'});log('worker','error','job_failed',{job_id:job.id,operation_id:job.operation_id,project_id:job.project_id,kind:job.kind,attempt:Number(current.attempts),code});}else log('worker','warn','job_retry_scheduled',{job_id:job.id,operation_id:job.operation_id,project_id:job.project_id,kind:job.kind,attempt:Number(current.attempts),code,retry_in_seconds:delay});});

const heartbeat=(job:any)=>setInterval(()=>{void pool.query(`UPDATE jobs SET heartbeat_at=clock_timestamp(),lease_expires_at=clock_timestamp()+($2||' seconds')::interval WHERE id=$1 AND status='LEASED'`,[job.id,String(leaseSeconds())]);},config().agentHeartbeatSeconds*1000);
export const runOnce=async(projectId?:string):Promise<boolean>=>{const lock=await pool.connect();try{if(!(await lock.query('SELECT pg_try_advisory_lock(941001) locked')).rows[0].locked)return false;const job=await leaseJob(projectId);if(!job)return false;log('worker','info','job_started',{job_id:job.id,operation_id:job.operation_id,project_id:job.project_id,kind:job.kind,attempt:Number(job.attempts)});const timer=heartbeat(job);let step='agent_readiness';try{if(job.kind==='DEVELOP_WORK_ITEM'){step='prepare_isolated_worktree';await prepareDevelopmentJob(job);step='persist_result';await completeJob(job);}else{if(job.kind!=='VALIDATE_INTAKE')await checkAgentReadiness();step='agent_invocation';const result=job.kind==='VALIDATE_INTAKE'?undefined:await (async()=>{const intake=(await pool.query('SELECT payload FROM intake_revisions WHERE id=$1',[job.revision_id])).rows[0].payload;const adjustment=(await pool.query(`SELECT payload->>'feedback' AS feedback FROM events WHERE project_id=$1 AND event_type='REVIEW_ADJUSTMENTS_APPLIED' ORDER BY id DESC LIMIT 1`,[job.project_id])).rows[0]?.feedback??null;return executeAgent(job.kind,{intake,project_id:job.project_id,review_adjustment_feedback:adjustment});})();step='persist_result';await completeJob(job,result);}log('worker','info','job_completed',{job_id:job.id,operation_id:job.operation_id,project_id:job.project_id,kind:job.kind,attempt:Number(job.attempts)});}catch(error){const cause=error as {code?:unknown;constraint?:unknown};log('worker','error','job_execution_failed',{job_id:job.id,operation_id:job.operation_id,project_id:job.project_id,kind:job.kind,attempt:Number(job.attempts),step,error_kind:error instanceof Error?error.constructor.name:'UnknownError',cause_code:typeof cause.code==='string'?cause.code:undefined,cause_constraint:typeof cause.constraint==='string'?cause.constraint:undefined});await failJob(job,error);}finally{clearInterval(timer);}return true;}finally{try{await lock.query('SELECT pg_advisory_unlock(941001)')}finally{lock.release()}}};
if(process.argv[1]?.endsWith('worker.ts')||process.argv[1]?.endsWith('worker.js')){log('worker','info','worker_started',{poll_interval_seconds:1});process.on('SIGTERM',()=>{log('worker','info','worker_stopped');process.exit(0)});while(true){try{await runOnce()}catch(error){log('worker','error','worker_cycle_failed',{error_kind:error instanceof Error?error.constructor.name:'UnknownError'})}await new Promise(r=>setTimeout(r,1000));}}
