import { randomUUID } from 'node:crypto';
import { pool, withTransaction } from './db.js';
import { putArtifact } from './artifacts.js';
import { validateIntake } from './service.js';
import { config } from './config.js';
import { transitionTarget } from './workflow.js';
import { executeAgent } from './agent.js';
const delays=[5,15,30];
const event=async(c:any,p:string,t:string,o:any,j:any,r:any,payload:object={})=>c.query(`INSERT INTO events(project_id,event_type,correlation_id,operation_id,job_id,revision_id,payload,actor_id,workflow_code,workflow_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'PROJECT_DISCOVERY',1)`,[p,t,randomUUID(),o,j,r,payload,config().operatorId]);
const nextJob=async(c:any,job:any,kind:string)=>{const id=randomUUID(); await c.query(`INSERT INTO jobs(id,operation_id,project_id,revision_id,kind,idempotency_key) VALUES($1,$2,$3,$4,$5,$6)`,[id,job.operation_id,job.project_id,job.revision_id,kind,`${kind}:${job.operation_id}`]); return id;};
export const runOnce=async():Promise<boolean>=>{const lock=await pool.connect(); try {if(!(await lock.query('SELECT pg_try_advisory_lock(941001) locked')).rows[0].locked)return false; return await withTransaction(async c=>{
 const q=await c.query(`WITH x AS (SELECT id FROM jobs WHERE (status IN ('PENDING','RETRYABLE') AND available_at<=now()) OR(status='LEASED' AND lease_expires_at<now()) ORDER BY available_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE jobs SET status='LEASED',attempts=attempts+1,lease_expires_at=now()+interval '2 minutes',heartbeat_at=now() WHERE id IN(SELECT id FROM x) RETURNING *`); if(!q.rowCount)return false; const job=q.rows[0]; await c.query(`UPDATE operations SET status='RUNNING' WHERE id=$1`,[job.operation_id]);
 try { const rev=(await c.query('SELECT payload FROM intake_revisions WHERE id=$1',[job.revision_id])).rows[0];
  if(job.kind==='VALIDATE_INTAKE'){const errors=validateIntake(rev.payload);await putArtifact(c,job.project_id,'validation-report',JSON.stringify({schema_version:1,result:errors.length?'INVALID':'VALID',errors}),job.id);if(errors.length){await event(c,job.project_id,'INTAKE_REQUIRES_ADJUSTMENT',job.operation_id,job.id,job.revision_id,{errors});}else{const gateId=randomUUID();await putArtifact(c,job.project_id,'gate-opened',JSON.stringify({gate_id:gateId}),job.id,gateId);const target=await transitionTarget(c,job.project_id,'INTAKE_VALIDATED');await c.query('UPDATE projects SET state=$2 WHERE id=$1',[job.project_id,target]);await c.query(`INSERT INTO gates(id,project_id,kind,revision_id) VALUES($1,$2,'REGISTER_PROJECT',$3)`,[gateId,job.project_id,job.revision_id]);await event(c,job.project_id,'INTAKE_VALIDATED',job.operation_id,job.id,job.revision_id);await event(c,job.project_id,'GATE_OPENED',job.operation_id,job.id,job.revision_id,{gate_id:gateId,kind:'REGISTER_PROJECT'});}}
  else {const result=await executeAgent(job.kind,{intake:rev.payload,project_id:job.project_id});const type=job.kind==='ANALYZE_PRODUCT_NEED'?'product-need-analysis':job.kind==='DEFINE_PRODUCT_REQUIREMENTS'?'product-requirements':'product-commitment-review';const artifact=await putArtifact(c,job.project_id,type,JSON.stringify({schema_version:1,correlation_id:job.operation_id,input_references:[],...result.evidence,result:result.result}),job.id); await c.query(`UPDATE artifacts SET metadata=$3 WHERE project_id=$1 AND storage_key=$2`,[job.project_id,artifact.key,result.evidence]); let trigger='',next=''; if(job.kind==='ANALYZE_PRODUCT_NEED'){trigger='ANALYSIS_COMPLETED';next='DEFINE_PRODUCT_REQUIREMENTS';}else if(job.kind==='DEFINE_PRODUCT_REQUIREMENTS'){trigger='REQUIREMENTS_COMPLETED';next='REVIEW_PRODUCT_COMMITMENT';}else if(result.result==='REQUIRES_ADJUSTMENT'){trigger='REVIEW_REQUIRES_ADJUSTMENT';next='DEFINE_PRODUCT_REQUIREMENTS';}else trigger='REVIEW_READY_FOR_GATE'; const target=await transitionTarget(c,job.project_id,trigger);await c.query('UPDATE projects SET state=$2,updated_at=now() WHERE id=$1',[job.project_id,target]);await event(c,job.project_id,trigger,job.operation_id,job.id,job.revision_id,{agent:job.kind,phase:type,evidence_type:type,evidence_hash:artifact.hash,result:result.result,next_action:next||'Aguardando sua decisão'});if(next)await nextJob(c,job,next);else {const gateId=randomUUID();const evidence=(await c.query(`SELECT artifact_type,sha256,metadata FROM artifacts WHERE project_id=$1 AND execution_id=$2 AND artifact_type IN ('product-need-analysis','product-requirements','product-commitment-review') ORDER BY created_at`,[job.project_id,job.operation_id])).rows;await c.query(`INSERT INTO gates(id,project_id,kind,revision_id,evidence) VALUES($1,$2,'PRODUCT_COMMITMENT',$3,$4)`,[gateId,job.project_id,job.revision_id,{evidence}]);await event(c,job.project_id,'GATE_OPENED',job.operation_id,job.id,job.revision_id,{gate_id:gateId,kind:'PRODUCT_COMMITMENT',evidence});}}
  await c.query(`UPDATE jobs SET status='COMPLETED',completed_at=now() WHERE id=$1`,[job.id]); const pending=await c.query(`SELECT 1 FROM jobs WHERE operation_id=$1 AND status IN('PENDING','RETRYABLE','LEASED')`,[job.operation_id]);if(!pending.rowCount)await c.query(`UPDATE operations SET status='SUCCEEDED',completed_at=now() WHERE id=$1`,[job.operation_id]);return true;
 } catch(e){const permanent=Number(job.attempts)>config().agentMaxRetries;await c.query(`UPDATE jobs SET status=$2,last_error=$3,available_at=now()+($4||' seconds')::interval,completed_at=CASE WHEN $2='FAILED' THEN now() END WHERE id=$1`,[job.id,permanent?'FAILED':'RETRYABLE','AGENT_EXECUTION_FAILED',String(delays[Math.min(Number(job.attempts)-1,2)])]);if(permanent){await c.query(`UPDATE operations SET status='FAILED',failure_code='AGENT_EXECUTION_FAILED',completed_at=now() WHERE id=$1`,[job.operation_id]);await event(c,job.project_id,'AGENT_EXECUTION_FAILED',job.operation_id,job.id,job.revision_id,{code:'AGENT_EXECUTION_FAILED',next_action:'Verifique a configuração do agente e tente novamente'});}return true;}
 });}finally{try{await lock.query('SELECT pg_advisory_unlock(941001)')}finally{lock.release()}}};
if(process.argv[1]?.endsWith('worker.ts')||process.argv[1]?.endsWith('worker.js'))while(true){await runOnce();await new Promise(r=>setTimeout(r,1000));}
