import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';

if (!process.env.DATABASE_URL) {
  test('GAT-02 final focused PostgreSQL proofs require DATABASE_URL', { skip: 'set DATABASE_URL' }, () => {});
} else {
  const { pool, withTransaction } = await import('./db.js');
  const { assurancePolicyHash } = await import('./assurance-expansion.js');
  const { decideReview } = await import('./assurance.js');
  const { decideDeliveryAcceptance, materializeDeliveryPackage, openDeliveryAcceptanceGate, persistDeliveryPreparationOutputs, prepareDeliveryPackage } = await import('./delivery-lifecycle.js');
  const { createProductCommitmentRevision, decideProductCommitmentGate } = await import('./product-commitment.js');

  const outputs={release_evidence:[{hash:'release-evidence'}],operation_evidence:[{hash:'operation-evidence'}],handover_evidence:[{hash:'handover-evidence'}],artifact_references:[{hash:'final-artifact'}]};
  type Fixture={project:string;module:string;revision:string;commitment:string;policy:string;runtime:string;executionPolicy:string;cleanup:()=>Promise<void>};

  const fixture=async():Promise<Fixture>=>{
    const project=`gat02-final-${randomUUID().slice(0,12)}`,intake=randomUUID(),commitment=randomUUID(),requirements=randomUUID(),review=randomUUID(),module=randomUUID(),revision=randomUUID(),obligation=randomUUID(),runtime=randomUUID(),executionPolicy=randomUUID(),policy=randomUUID();
    const selectors={jobKinds:['PREPARE_DELIVERY_PACKAGE'],subjectKinds:['DeliveryPackage:v1'],taskTypes:['PREPARE_DELIVERY_PACKAGE'],classifications:['INTERNAL']},configuration={schema_version:1,rollout_id:`gat02-${project}`,reviewer_runtime_ids:[runtime]};
    await withTransaction(async client=>{
      await client.query(`INSERT INTO projects(id,title,business_owner,submitted_by,repository_path,repository_origin,base_branch,initial_sha,workflow_code,workflow_version,state,draft) VALUES($1,'GAT-02 final','owner','test','/tmp','local','main','000','PROJECT_DISCOVERY',4,'DELIVERY','{}')`,[project]);
      await client.query(`INSERT INTO intake_revisions(id,project_id,schema_version,payload,structured_sha256,markdown_sha256,artifact_uri,submitted_by) VALUES($1,$2,1,'{}',$3,$4,'file:///tmp/intake','test')`,[intake,project,'a'.repeat(64),'b'.repeat(64)]);
      await client.query(`INSERT INTO artifacts(id,project_id,artifact_type,storage_uri,storage_key,sha256,schema_version) VALUES($1::uuid,$3,'product-requirements','file:///tmp/requirements',$1::text,$4,1),($2::uuid,$3,'product-commitment-review','file:///tmp/review',$2::text,$5,1)`,[requirements,review,project,'c'.repeat(64),'d'.repeat(64)]);
      await client.query(`INSERT INTO product_commitment_revisions(id,project_id,revision_number,logical_round,contract_version,status,source_intake_revision_id,source_requirements_artifact_id,source_requirements_sha256,source_review_artifact_id,source_review_sha256,canonical_sha256,creation_idempotency_key,approved_at,created_by) VALUES($1,$2,1,1,'PRODUCT_COMMITMENT_MODULES:v1','APPROVED',$3,$4,$5,$6,$7,$8,$9,clock_timestamp(),'test')`,[commitment,project,intake,requirements,'c'.repeat(64),review,'d'.repeat(64),'e'.repeat(64),`commitment:${project}`]);
      await client.query(`INSERT INTO module_revisions(id,project_id,module_key,revision,payload,status) VALUES($1,$2,'delivery-module',1,'{}','APPROVED')`,[revision,project]);
      await client.query(`INSERT INTO modules(id,project_id,module_key,current_revision_id,state,workflow_code,workflow_version) VALUES($1,$2,'delivery-module',$3,'READY_FOR_DELIVERY','MODULE_DELIVERY',2)`,[module,project,revision]);
      await client.query(`INSERT INTO committed_module_obligations(id,project_id,module_key,generation,required,materialized_module_id,materialized_module_revision_id,introduced_by_revision_id,last_present_revision_id) VALUES($1,$2,'delivery-module',1,true,$3,$4,$5,$5)`,[obligation,project,module,revision,commitment]);
      await client.query(`INSERT INTO ai_runtime(id,name,environment,enabled,current_configuration_version) VALUES($1,$2,'test',true,1)`,[runtime,`gat02-final-${runtime}`]);
      await client.query(`INSERT INTO ai_runtime_configuration(runtime_id,version,adapter_type,model,quality_tier,timeout_seconds,auth_type,configuration,created_by,change_reason) VALUES($1,1,'CODEX_CLI','controlled','HIGH',60,'NONE','{}','test','GAT-02 final')`,[runtime]);
      await client.query(`INSERT INTO agent_execution_policy(id,name,version,selectors,primary_runtime_id,published_at,published_by) VALUES($1,$2,1,'{}',$3,clock_timestamp(),'test')`,[executionPolicy,`gat02-final-${executionPolicy}`,runtime]);
      await client.query(`INSERT INTO assurance_policies(id,name,version,enabled,selectors,configuration,policy_hash,published_by) VALUES($1,$2,1,true,$3,$4,$5,'test')`,[policy,`gat02-final-${policy}`,selectors,configuration,assurancePolicyHash(selectors,configuration)]);
    });
    // AUT-03 dispatch snapshots are deliberately non-deletable audit evidence.
    // This disposable integration database therefore retains each isolated,
    // UUID-keyed fixture, matching the existing AUT-03 focused proofs.
    const cleanup=async()=>{};
    return {project,module,revision,commitment,policy,runtime,executionPolicy,cleanup};
  };
  const prepared=async(f:Fixture)=>{const snapshot:any=await prepareDeliveryPackage(f.project,`prepare:${f.project}`);await persistDeliveryPreparationOutputs(snapshot.id,outputs);const pkg:any=await materializeDeliveryPackage(snapshot.id);return {snapshot,pkg};};
  const accept=async(pkg:any)=>{const dispatch=(await pool.query(`SELECT * FROM assurance_dispatch_snapshots WHERE subject_kind='DeliveryPackage:v1' AND subject_id=$1`,[pkg.id])).rows[0];assert.ok(dispatch);const acceptance=(await pool.query(`SELECT * FROM work_acceptances WHERE assurance_dispatch_snapshot_id=$1`,[dispatch.id])).rows[0];const review=(await pool.query(`SELECT * FROM assurance_reviews WHERE acceptance_id=$1`,[acceptance.id])).rows[0];assert.ok(review);await decideReview(review.id,'ACCEPT',{evidence:{review:'accepted'}},`accept:${review.id}`);return {dispatch,acceptance,review,technical:(await pool.query(`SELECT * FROM delivery_technical_acceptances WHERE package_id=$1`,[pkg.id])).rows[0]};};
  const gate=async(f:Fixture,pkg:any)=>{await accept(pkg);return openDeliveryAcceptanceGate(pkg.id) as any;};
  const input=(gate:any,decision:'APPROVE'|'REWORK',key:string)=>({version:Number(gate.version),decision,reason:decision==='APPROVE'?'Business acceptance.':'Correct the handover.',evidence:decision==='APPROVE'?{handover:'verified'}:{finding:'Incomplete handover.'},actor_id:'business-owner',actor_role:'BUSINESS_OWNER',idempotency_key:key});

  test('GAT-02 AUT-03 release path freezes exact package lineage and ACCEPT is technical only',async t=>{
    const f=await fixture();t.after(f.cleanup);const {snapshot,pkg}=await prepared(f);const accepted=await accept(pkg);
    assert.equal(accepted.dispatch.subject_kind,'DeliveryPackage:v1');assert.equal(accepted.dispatch.subject_id,pkg.id);assert.equal(accepted.dispatch.normative_generation,pkg.normative_generation);assert.equal(accepted.dispatch.assurance_dispatch_key,`assurance-dispatch:v1:DeliveryPackage:v1:${pkg.id}:${pkg.normative_generation}`);assert.equal(accepted.dispatch.policy_id,f.policy);assert.equal(Number(accepted.dispatch.policy_version),1);assert.match(accepted.dispatch.policy_hash,/^[a-f0-9]{64}$/);assert.equal(accepted.acceptance.assurance_dispatch_snapshot_id,accepted.dispatch.id);assert.equal(accepted.technical.assurance_dispatch_snapshot_id,accepted.dispatch.id);assert.equal(accepted.technical.work_acceptance_id,accepted.acceptance.id);assert.equal(accepted.technical.content_hash,pkg.content_hash);assert.equal(Number(accepted.technical.delivery_revision),Number(pkg.delivery_revision));assert.equal(accepted.technical.normative_generation,pkg.normative_generation);
    assert.equal((await pool.query(`SELECT state FROM projects WHERE id=$1`,[f.project])).rows[0].state,'DELIVERY');assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM gate_records WHERE project_id=$1 AND gate_code='DELIVERY_ACCEPTANCE'`,[f.project])).rows[0].n),0);
    await assert.rejects((await import('./delivery-lifecycle.js')).recordTechnicalAcceptance(pkg.id,{assurance_dispatch_snapshot_id:accepted.dispatch.id,work_acceptance_id:randomUUID()}),(error:any)=>error.code==='TECHNICAL_ACCEPTANCE_BINDING_INVALID');
    await assert.rejects((await import('./delivery-lifecycle.js')).recordTechnicalAcceptance(pkg.id,{assurance_dispatch_snapshot_id:randomUUID(),work_acceptance_id:accepted.acceptance.id}),(error:any)=>error.code==='TECHNICAL_ACCEPTANCE_BINDING_INVALID');
    await assert.rejects((await import('./delivery-lifecycle.js')).recordTechnicalAcceptance(randomUUID(),{assurance_dispatch_snapshot_id:accepted.dispatch.id,work_acceptance_id:accepted.acceptance.id}),(error:any)=>error.code==='DELIVERY_PACKAGE_NOT_FOUND');
    assert.equal((await materializeDeliveryPackage(snapshot.id)).id,pkg.id);assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM delivery_technical_acceptances WHERE package_id=$1`,[pkg.id])).rows[0].n),1);
    const negative=await fixture();t.after(negative.cleanup);const negativePkg=(await prepared(negative)).pkg;const negativeDispatch=(await pool.query(`SELECT id FROM assurance_dispatch_snapshots WHERE subject_kind='DeliveryPackage:v1' AND subject_id=$1`,[negativePkg.id])).rows[0],negativeAcceptance=(await pool.query(`SELECT id FROM work_acceptances WHERE assurance_dispatch_snapshot_id=$1`,[negativeDispatch.id])).rows[0],negativeReview=(await pool.query(`SELECT id FROM assurance_reviews WHERE acceptance_id=$1`,[negativeAcceptance.id])).rows[0];await decideReview(negativeReview.id,'REWORK',{evidence:{description:'Release needs correction.'}},`rework:${negativeReview.id}`);assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM delivery_technical_acceptances WHERE package_id=$1`,[negativePkg.id])).rows[0].n),0);assert.equal((await pool.query(`SELECT state FROM projects WHERE id=$1`,[negative.project])).rows[0].state,'DELIVERY');
  });

  test('GAT-02 APPROVE is all-or-nothing when a realistic database failure occurs mid-transition',async t=>{
    const f=await fixture();t.after(async()=>{await pool.query(`DROP TRIGGER IF EXISTS gat02_rollback_modules ON modules`);await pool.query(`DROP FUNCTION IF EXISTS gat02_rollback_modules()`);await f.cleanup();});const {pkg}=await prepared(f);const deliveryGate:any=await gate(f,pkg);
    await pool.query(`CREATE FUNCTION gat02_rollback_modules() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.project_id='${f.project}' AND NEW.state='DELIVERED' THEN RAISE EXCEPTION 'GAT02_FORCED_MODULE_FAILURE'; END IF; RETURN NEW; END $$`);
    await pool.query(`CREATE TRIGGER gat02_rollback_modules BEFORE UPDATE ON modules FOR EACH ROW EXECUTE FUNCTION gat02_rollback_modules()`);
    await assert.rejects(decideDeliveryAcceptance(f.project,deliveryGate.id,input(deliveryGate,'APPROVE',`rollback:${f.project}`)),/GAT02_FORCED_MODULE_FAILURE/);
    assert.equal((await pool.query(`SELECT state FROM projects WHERE id=$1`,[f.project])).rows[0].state,'DELIVERY');assert.equal((await pool.query(`SELECT state FROM modules WHERE id=$1`,[f.module])).rows[0].state,'READY_FOR_DELIVERY');assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM committed_module_obligations WHERE project_id=$1 AND delivered_at IS NOT NULL`,[f.project])).rows[0].n),0);assert.equal((await pool.query(`SELECT delivered_at FROM delivery_packages WHERE id=$1`,[pkg.id])).rows[0].delivered_at,null);assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM gate_decisions WHERE gate_id=$1`,[deliveryGate.id])).rows[0].n),0);assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM operations WHERE project_id=$1 AND kind='DELIVERY_TRANSITION'`,[f.project])).rows[0].n),0);assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM events WHERE project_id=$1 AND event_type='PROJECT_DELIVERED'`,[f.project])).rows[0].n),0);
  });

  test('GAT-02 competing decisions have one authoritative terminal outcome and replay converges',async t=>{
    const f=await fixture();t.after(f.cleanup);const {pkg}=await prepared(f);const deliveryGate:any=await gate(f,pkg);const approved=input(deliveryGate,'APPROVE',`race-approve:${f.project}`),reworked=input(deliveryGate,'REWORK',`race-rework:${f.project}`);const outcomes=await Promise.allSettled([decideDeliveryAcceptance(f.project,deliveryGate.id,approved),decideDeliveryAcceptance(f.project,deliveryGate.id,reworked)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal(outcomes.filter(x=>x.status==='rejected').length,1);const decision=(await pool.query(`SELECT decision FROM gate_decisions WHERE gate_id=$1`,[deliveryGate.id])).rows[0].decision;assert.ok(decision==='APPROVE'||decision==='REWORK');assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM gate_decisions WHERE gate_id=$1`,[deliveryGate.id])).rows[0].n),1);const state=(await pool.query(`SELECT state FROM projects WHERE id=$1`,[f.project])).rows[0].state;assert.equal(state,decision==='APPROVE'?'DELIVERED':'VALIDATION');assert.equal((await decideDeliveryAcceptance(f.project,deliveryGate.id,decision==='APPROVE'?approved:reworked) as any).state,state);
  });

  test('GAT-02 HTTP accepts only explicit BUSINESS_OWNER APPROVE and REWORK decisions',async t=>{
    const { createApiServer }=await import('./server.js');const { testAuthenticatedHeaders }=await import('./test-auth.js');const f=await fixture(),r=await fixture();t.after(f.cleanup);t.after(r.cleanup);const server=createApiServer();await new Promise<void>(ok=>server.listen(0,'127.0.0.1',ok));const base=`http://127.0.0.1:${(server.address() as any).port}`;t.after(()=>server.close());
    const fGate:any=await gate(f,(await prepared(f)).pkg),rGate:any=await gate(r,(await prepared(r)).pkg);const fOwner=await testAuthenticatedHeaders(f.project,[{role_code:'BUSINESS_OWNER',action_code:'DECIDE_CATALOG_GATE',project_id:f.project,resource_type:'PROJECT',resource_id:f.project}]),rOwner=await testAuthenticatedHeaders(r.project,[{role_code:'BUSINESS_OWNER',action_code:'DECIDE_CATALOG_GATE',project_id:r.project,resource_type:'PROJECT',resource_id:r.project}]);t.after(fOwner.cleanup);t.after(rOwner.cleanup);
    const call=(project:string,gateId:string,headers:Record<string,string>,decision:'APPROVE'|'REWORK',key:string)=>fetch(`${base}/api/projects/${project}/delivery/gates/${gateId}/decision`,{method:'POST',headers:{...headers,'content-type':'application/json','idempotency-key':key},body:JSON.stringify({...input(decision==='APPROVE'?fGate:rGate,decision,key),version:1,decision})});
    assert.equal((await call(f.project,fGate.id,fOwner.headers,'APPROVE',`http-approve:${f.project}`)).status,202);assert.equal((await pool.query(`SELECT state FROM projects WHERE id=$1`,[f.project])).rows[0].state,'DELIVERED');assert.equal((await call(r.project,rGate.id,rOwner.headers,'REWORK',`http-rework:${r.project}`)).status,202);assert.equal((await pool.query(`SELECT state FROM projects WHERE id=$1`,[r.project])).rows[0].state,'VALIDATION');
  });

  test('GAT-02 consumers revalidate required set, participant revision, workflow and frozen gate identity',async t=>{
    const f=await fixture();t.after(f.cleanup);const {pkg}=await prepared(f);await accept(pkg);const addedModule=randomUUID(),addedRevision=randomUUID(),addedObligation=randomUUID();await pool.query(`INSERT INTO module_revisions(id,project_id,module_key,revision,payload,status) VALUES($1,$2,'added-module',1,'{}','APPROVED')`,[addedRevision,f.project]);await pool.query(`INSERT INTO modules(id,project_id,module_key,current_revision_id,state,workflow_code,workflow_version) VALUES($1,$2,'added-module',$3,'READY_FOR_DELIVERY','MODULE_DELIVERY',2)`,[addedModule,f.project,addedRevision]);await pool.query(`INSERT INTO committed_module_obligations(id,project_id,module_key,generation,required,materialized_module_id,materialized_module_revision_id,introduced_by_revision_id,last_present_revision_id) VALUES($1,$2,'added-module',1,true,$3,$4,$5,$5)`,[addedObligation,f.project,addedModule,addedRevision,f.commitment]);await assert.rejects(openDeliveryAcceptanceGate(pkg.id),(error:any)=>error.code==='STALE_DELIVERY_PACKAGE');
    const g=await fixture();t.after(g.cleanup);const preparedRevision=await prepared(g);await accept(preparedRevision.pkg);const replacementRevision=randomUUID();await pool.query(`INSERT INTO module_revisions(id,project_id,module_key,revision,payload,status) VALUES($1,$2,'delivery-module',2,'{}','APPROVED')`,[replacementRevision,g.project]);await pool.query(`UPDATE modules SET current_revision_id=$2 WHERE id=$1`,[g.module,replacementRevision]);await assert.rejects(openDeliveryAcceptanceGate(preparedRevision.pkg.id),(error:any)=>error.code==='STALE_DELIVERY_PACKAGE');
    const h=await fixture();t.after(h.cleanup);const preparedCommitment=await prepared(h);await accept(preparedCommitment.pkg);const deliveryGate:any=await openDeliveryAcceptanceGate(preparedCommitment.pkg.id);const lineage=(await pool.query(`SELECT source_intake_revision_id,source_requirements_artifact_id,source_review_artifact_id FROM product_commitment_revisions WHERE id=$1`,[h.commitment])).rows[0];const proposal={contract_version:'PRODUCT_COMMITMENT_MODULES:v1',candidate_modules:[{module_key:'delivery-module',name:'Delivery module',objective:'Revised delivery commitment',scope:['Delivery'],out_of_scope:['None'],dependencies:[],acceptance_criteria:['Ready for delivery'],source_evidence:{requirement_refs:['REQ-1'],artifact_refs:[{artifact_id:lineage.source_requirements_artifact_id,sha256:'c'.repeat(64)}]}}],investment_and_risks:{investment:['Incremental'],risks:['Reviewed']}};const successor:any=await withTransaction(client=>createProductCommitmentRevision(client,h.project,proposal,lineage,`replacement-commitment:${h.project}`));await decideProductCommitmentGate(h.project,successor.gate_record_id,{version:1,decision:'APPROVE',reason:'Successor commitment approved.',evidence:{acknowledged:true},actor_id:'business-owner',actor_role:'BUSINESS_OWNER',idempotency_key:`approve-replacement:${h.project}`});await assert.rejects(decideDeliveryAcceptance(h.project,deliveryGate.id,input(deliveryGate,'APPROVE',`stale-commitment:${h.project}`)),(error:any)=>error.code==='STALE_DELIVERY_PACKAGE');
    const i=await fixture();t.after(i.cleanup);const preparedGate=await prepared(i);await accept(preparedGate.pkg);const identityGate:any=await openDeliveryAcceptanceGate(preparedGate.pkg.id);await pool.query(`UPDATE gate_records SET evidence=jsonb_set(evidence,'{normative_generation}','"${'0'.repeat(64)}"'::jsonb) WHERE id=$1`,[identityGate.id]);await assert.rejects(decideDeliveryAcceptance(i.project,identityGate.id,input(identityGate,'APPROVE',`stale-generation:${i.project}`)),(error:any)=>error.code==='STALE_DELIVERY_PACKAGE');
  });

  test.after(async()=>pool.end());
}
