import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';

if(!process.env.DATABASE_URL) test('GAT-02 HTTP/RBAC proof requires DATABASE_URL',{skip:'set DATABASE_URL'},()=>{});
else {
  const { pool }=await import('./db.js');
  const { createApiServer }=await import('./server.js');
  const { createServicePrincipal }=await import('./auth.js');
  const { testAuthenticatedHeaders }=await import('./test-auth.js');
  const project=`gat02-http-${randomUUID().slice(0,12)}`,other=`gat02-http-other-${randomUUID().slice(0,10)}`,module=randomUUID(),revision=randomUUID(),extra=randomUUID(),extraRevision=randomUUID();
  const post=(base:string,path:string,headers:Record<string,string>,body:unknown,key=path)=>fetch(`${base}${path}`,{method:'POST',headers:{...headers,'content-type':'application/json','idempotency-key':`${key}:${randomUUID()}`},body:JSON.stringify(body)});
  test('GAT-02 HTTP delivery endpoints authorize persisted grants only and reject spoofing',async t=>{
    await pool.query(`INSERT INTO projects(id,title,business_owner,submitted_by,repository_path,repository_origin,base_branch,initial_sha,workflow_code,workflow_version,state,draft) VALUES($1,'GAT-02 HTTP','owner','test','/tmp','local','main','000','PROJECT_DISCOVERY',4,'DELIVERY','{}'),($2,'GAT-02 HTTP other','owner','test','/tmp','local','main','000','PROJECT_DISCOVERY',4,'DELIVERY','{}')`,[project,other]);
    await pool.query(`INSERT INTO module_revisions(id,project_id,module_key,revision,payload,status) VALUES($1,$2,'delivery-module',1,'{}','APPROVED'),($3,$2,'non-required',1,'{}','APPROVED')`,[revision,project,extraRevision]);
    await pool.query(`INSERT INTO modules(id,project_id,module_key,current_revision_id,state,workflow_code,workflow_version) VALUES($1,$2,'delivery-module',$3,'READY_FOR_DELIVERY','MODULE_DELIVERY',2),($4,$2,'non-required',$5,'READY_FOR_DELIVERY','MODULE_DELIVERY',2)`,[module,project,revision,extra,extraRevision]);
    const onCall=await testAuthenticatedHeaders(project,[{role_code:'ON_CALL_OWNER',action_code:'DELIVERY_PAUSE_RESUME',project_id:project,resource_type:'PROJECT',resource_id:project},{role_code:'ON_CALL_OWNER',action_code:'DELIVERY_PAUSE_RESUME',project_id:project,resource_type:'MODULE',resource_id:module}]);
    const owner=await testAuthenticatedHeaders(project,[{role_code:'BUSINESS_OWNER',action_code:'DELIVERY_CANCEL',project_id:project,resource_type:'PROJECT',resource_id:project},{role_code:'BUSINESS_OWNER',action_code:'DELIVERY_CANCEL',project_id:project,resource_type:'MODULE',resource_id:extra},{role_code:'BUSINESS_OWNER',action_code:'DECIDE_CATALOG_GATE',project_id:project,resource_type:'PROJECT',resource_id:project}]);
    const wrongScope=await testAuthenticatedHeaders(project,[{role_code:'ON_CALL_OWNER',action_code:'DELIVERY_PAUSE_RESUME',project_id:other,resource_type:'PROJECT',resource_id:other}]);
    const expired=await testAuthenticatedHeaders(project,[{role_code:'ON_CALL_OWNER',action_code:'DELIVERY_PAUSE_RESUME',project_id:project,resource_type:'PROJECT',resource_id:project,expires_at:'2000-01-01T00:00:00Z'}]);
    const service:any=await createServicePrincipal({username:`gat02-service-${randomUUID().slice(0,8)}`,grants:[{role_code:'WORKER_SERVICE',action_code:'DELIVERY_EXECUTE',project_id:project}]});
    const humanSpoof=await testAuthenticatedHeaders(project,[{role_code:'AGENT_SERVICE',action_code:'DELIVERY_EXECUTE',project_id:project}]);
    const server=createApiServer();await new Promise<void>(ok=>server.listen(0,'127.0.0.1',ok));const base=`http://127.0.0.1:${(server.address() as any).port}`;
    t.after(async()=>{server.close();await onCall.cleanup();await owner.cleanup();await wrongScope.cleanup();await expired.cleanup();await humanSpoof.cleanup();await pool.query(`DELETE FROM auth_audit_records WHERE principal_id=$1`,[service.principal_id]);await pool.query(`DELETE FROM auth_credentials WHERE principal_id=$1`,[service.principal_id]);await pool.query(`DELETE FROM auth_role_grants WHERE principal_id=$1`,[service.principal_id]);await pool.query(`DELETE FROM auth_principals WHERE id=$1`,[service.principal_id]);await pool.query(`DELETE FROM resume_records WHERE pause_id IN (SELECT id FROM pause_records WHERE project_id=$1)`,[project]);await pool.query(`DELETE FROM pause_records WHERE project_id=$1`,[project]);await pool.query(`DELETE FROM cancellation_records WHERE project_id=$1`,[project]);await pool.query(`DELETE FROM events WHERE project_id=$1`,[project]);await pool.query(`DELETE FROM modules WHERE project_id=$1`,[project]);await pool.query(`DELETE FROM module_revisions WHERE project_id=$1`,[project]);await pool.query(`DELETE FROM projects WHERE id IN ($1,$2)`,[project,other]);await pool.end();});
    const pause:any=await post(base,`/api/projects/${project}/delivery/pause`,onCall.headers,{reason:'maintenance',evidence:{ticket:'OPS-2'},actor_id:'spoof',authority_role:'BUSINESS_OWNER'},'pause');assert.equal(pause.status,202);const paused=await pause.json();assert.equal((await pool.query(`SELECT state FROM projects WHERE id=$1`,[project])).rows[0].state,'PAUSED');
    assert.equal((await post(base,`/api/projects/${project}/delivery/pauses/${paused.id}/resume`,onCall.headers,{expected_pause_version:1,evidence:{resolved:true}},'resume')).status,202);
    const modulePause:any=await post(base,`/api/projects/${project}/modules/${module}/lifecycle/pause`,onCall.headers,{reason:'module maintenance',evidence:{ticket:'OPS-3'}},'module-pause');assert.equal(modulePause.status,202);const modulePauseBody=await modulePause.json();assert.equal((await post(base,`/api/projects/${project}/delivery/pauses/${modulePauseBody.id}/resume`,onCall.headers,{expected_pause_version:1,evidence:{resolved:true}},'module-resume')).status,202);
    assert.equal((await post(base,`/api/projects/${project}/delivery/cancel`,onCall.headers,{reason:'spoofed cancel',evidence:{ok:true},authority_role:'BUSINESS_OWNER'},'oncall-cancel')).status,403);assert.equal((await post(base,`/api/projects/${project}/delivery/gates/${randomUUID()}/decision`,onCall.headers,{version:1,decision:'APPROVE',reason:'spoof',evidence:{ok:true},actor_role:'BUSINESS_OWNER'},'oncall-gate')).status,403);
    assert.equal((await post(base,`/api/projects/${project}/delivery/pause`,owner.headers,{reason:'owner pause',evidence:{ok:true}},'owner-pause')).status,403);assert.equal((await post(base,`/api/projects/${project}/delivery/pause`,wrongScope.headers,{reason:'wrong project',evidence:{ok:true}},'scope')).status,403);assert.equal((await post(base,`/api/projects/${project}/delivery/pause`,expired.headers,{reason:'expired',evidence:{ok:true}},'expired')).status,403);
    const serviceHeaders={authorization:`Service ${service.principal_id}:${service.credential}`,'x-actor-role':'BUSINESS_OWNER'};assert.equal((await post(base,`/api/projects/${project}/delivery/packages/${randomUUID()}/materialize`,serviceHeaders,{},'service')).status,404);assert.equal((await post(base,`/api/projects/${project}/delivery/gates/${randomUUID()}/decision`,serviceHeaders,{version:1,decision:'APPROVE',reason:'spoof',evidence:{ok:true}},'service-gate')).status,403);assert.equal((await post(base,`/api/projects/${project}/delivery/prepare`,humanSpoof.headers,{actor_role:'AGENT_SERVICE'},'human-service')).status,403);
    for(const decision of [undefined,'REJECT','APROVE','anything',null,{}]) assert.equal((await post(base,`/api/projects/${project}/delivery/gates/${randomUUID()}/decision`,owner.headers,{version:1,decision,reason:'invalid',evidence:{ok:true},actor_id:'spoof',actor_role:'ON_CALL_OWNER'},`invalid-${String(decision)}`)).status,422);assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM gate_decisions WHERE actor_id IN ('spoof','')`,[])).rows[0].n),0);
    assert.equal((await post(base,`/api/projects/${project}/modules/${extra}/lifecycle/cancel`,owner.headers,{reason:'business cancellation',evidence:{approved:true}},'module-cancel')).status,202);assert.equal((await post(base,`/api/projects/${project}/delivery/cancel`,owner.headers,{reason:'business cancellation',evidence:{approved:true}},'project-cancel')).status,202);
  });
}
