/** Closed, display-only contract for the module plan review screen (F5-24). */
const text=(value:unknown,max=2000)=>{if(typeof value!=='string')return '';const clean=value.replace(/[\x00-\x1f\x7f]/g,' ').trim().slice(0,max);return /(?:\b(?:prompt|secret|password|token|api[_-]?key)\b\s*[:=]|-----BEGIN|\/[^\s]+\/\.env)/i.test(clean)?'[redacted]':clean;};
const list=(value:unknown,max=50,maxText=500)=>Array.isArray(value)?value.slice(0,max).map(v=>text(v,maxText)).filter(Boolean):[];
const object=(value:unknown):Record<string,any>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:{};
const hash=(value:unknown)=>typeof value==='string'&&/^[a-f0-9]{64}$/i.test(value)?value:null;
const id=(value:unknown)=>typeof value==='string'?text(value,100):'';
const safePath=(value:unknown)=>{if(typeof value!=='string')return '';const raw=value.replace(/[\x00-\x1f\x7f]/g,' ').trim().slice(0,256);if(!raw||raw.startsWith('/')||raw.includes('\\')||raw.split('/').includes('..'))return '';return text(raw,256);};
const qa=(value:unknown)=>Array.isArray(value)?value.slice(0,20).map(entry=>{const q=object(entry);return {command:text(q.command,500),cwd:safePath(q.cwd),timeout_seconds:Number.isInteger(q.timeout_seconds)?q.timeout_seconds:0,environment:text(q.environment,100),criterion_ids:list(q.criterion_ids,30,100),kind:text(q.kind,100)};}):[];
const paths=(value:unknown,max=50)=>Array.isArray(value)?value.slice(0,max).map(safePath).filter(Boolean):[];
const workItem=(value:unknown,blocked:Map<string,string>)=>{const wi=object(value),logical_id=id(wi.work_item_id||wi.logical_id),depends_on_ids=list(wi.depends_on_ids,30,100),externalBlock=blocked.get(logical_id)??null,dependencyBlock=depends_on_ids.length?`Aguarda a conclusão de ${depends_on_ids.join(', ')}.`:null,blocked_reason=externalBlock??dependencyBlock;return {logical_id,title:text(wi.title,200),objective:text(wi.objective),inputs:list(wi.inputs,20),output:text(wi.output),acceptance_criteria:list(wi.acceptance_criteria,20),criterion_ids:list(wi.criterion_ids,30,100),allowlist:paths(wi.allowlist),denylist:paths(wi.denylist),depends_on_ids,qa_matrix:qa(wi.qa_matrix),risks:list(wi.risks,30),capabilities:list(wi.capabilities,10,100),status:text(wi.status,100)||'PROPOSED',eligible:!blocked_reason,blocked_reason,evidence:{json_hash:hash(wi.json_artifact_hash||wi.evidence_hash),markdown_hash:hash(wi.markdown_artifact_hash)}};};

export const modulePlanReview=(modules:any[],plans:any[],gates:any[])=>modules.map(module=>{
  const own=plans.filter(plan=>plan.module_id===module.id).sort((a,b)=>Number(b.revision_number)-Number(a.revision_number));
  const current=own[0]; if(!current)return null;
  const payload=object(current.payload), dependencies=Array.isArray(payload.business_dependency_coverage)?payload.business_dependency_coverage:[];
  const blockers=new Map<string,string>();
  for(const dependency of dependencies){const d=object(dependency);if(d.classification==='EXTERNAL_BLOCKER')for(const wi of list(d.blocked_work_item_ids,40,100))blockers.set(wi,text(d.justification,2000)||'Dependência externa pendente.');}
  const items=(Array.isArray(payload.work_items)?payload.work_items:[]).slice(0,40).map(wi=>workItem(wi,blockers));
  const coverage=(Array.isArray(payload.criterion_coverage)?payload.criterion_coverage:[]).slice(0,60).map(entry=>{const c=object(entry);return {criterion_id:id(c.criterion_id),work_item_ids:list(c.work_item_ids,40,100)};});
  const gate=gates.find(value=>value.module_id===module.id&&value.plan_revision_id===current.id&&value.kind==='MODULE_PLAN_APPROVAL')??null;
  const history=own.slice(0,20).map(revision=>({id:revision.id,number:Number(revision.revision_number),status:text(revision.status,100),author:{id:text(revision.author_id,100),label:text(revision.author_id,100)},created_at:revision.created_at,supersedes_revision_id:revision.supersedes_revision_id??null,feedback:text(revision.feedback,1000)||null,evidence:{json_hash:hash(revision.json_artifact_hash),markdown_hash:hash(revision.markdown_artifact_hash)}}));
  const currentIsOpen=current.status==='PLAN_PROPOSED'&&gate?.status==='OPEN';
  const alerts:any[]=[];
  if(!currentIsOpen){for(const gap of list(payload.gaps,30))alerts.push({code:'LEGACY_PLAN_GAP',severity:'WARNING',revision_id:current.id,work_item_id:null,message:gap});}
  return {schema_version:'module-plan-review/v1',module:{id:module.id,key:text(module.module_key,100),objective:text(module.objective),workflow_code:text(module.workflow_code,100),workflow_version:Number(module.workflow_version),state:text(module.state,100),canonical_state:text(module.canonical_state,100)},current_revision:{id:current.id,number:Number(current.revision_number),status:text(current.status,100),work_item_workflow:{code:text(current.work_item_workflow_code,100),version:Number(current.work_item_workflow_version)},supersedes_revision_id:current.supersedes_revision_id??null,created_at:current.created_at,author:{id:text(current.author_id,100),label:text(current.author_id,100)},baseline:{revision_id:current.technology_baseline_revision_id??null,label:null},evidence:{json_hash:hash(current.json_artifact_hash),markdown_hash:hash(current.markdown_artifact_hash)}},current_gate:gate?{id:gate.id,version:Number(gate.version),status:text(gate.status,100)}:null,summary:{work_item_count:items.length,eligible_count:items.filter(item=>item.eligible).length,blocked_count:items.filter(item=>!item.eligible).length,criterion_count:coverage.length,covered_criterion_count:coverage.filter(item=>item.work_item_ids.length>0).length},work_items:items,criterion_coverage:coverage,business_dependencies:dependencies.slice(0,30).map(entry=>{const d=object(entry);return {dependency_id:id(d.dependency_id),classification:text(d.classification,100),work_item_ids:list(d.work_item_ids,40,100),blocked_work_item_ids:list(d.blocked_work_item_ids,40,100),justification:text(d.justification)};}),revision_history:history,history_truncated:own.length>20,alerts};
}).filter(Boolean);
