import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import test from 'node:test';

process.env.DATABASE_URL ??= 'postgres://unused:unused@127.0.0.1:1/unused';
process.env.NAAMIVE_ARTIFACT_STORE_URI ??= `file://${process.cwd()}/.selection-context-artifacts`;
process.env.NAAMIVE_OPERATOR_ID ??= 'selection-context-tester';

if (process.env.DATABASE_URL.includes('unused')) test('selection context integration requires DATABASE_URL', { skip: 'set DATABASE_URL' }, () => {});
else {
  const { pool, withTransaction } = await import('./db.js');
  const { loadCatalogSeedPackage, catalogPackageHash, publishTechnologyCatalog } = await import('./catalog-publisher.js');
  const { validateTechnologyCatalogSeedPackage } = await import('./technology-contracts.js');
  const { prepareTechnologySelectionContext } = await import('./selection-context.js');
  const { startTechnologyInventory } = await import('./inventory.js');
  const { archiveProject } = await import('./service.js');
  const { runOnce } = await import('./worker.js');
  const base: any = await loadCatalogSeedPackage(); let number = Date.now() * 1000;
  const publish = async () => { const seed = structuredClone(base); seed.catalog_revision = ++number; for (const key of ['categories','catalogItems','profiles','profileItems','compatibilityRules','catalogRevision']) seed[key].catalog_revision=seed.catalog_revision; seed.catalogRevision.records[0].catalog_revision=seed.catalog_revision; seed.catalogRevision.records[0].content_hash=catalogPackageHash(await validateTechnologyCatalogSeedPackage(seed)); return publishTechnologyCatalog(seed, 'selection-context-tester', randomUUID()); };
  const setup = async (state='TECHNOLOGY_SELECTION_PREPARING') => { const id=randomUUID(), revision=randomUUID(), operation=randomUUID(), job=randomUUID(), correlation=randomUUID(); await pool.query(`INSERT INTO projects(id,title,business_owner,submitted_by,repository_path,repository_origin,base_branch,initial_sha,workflow_code,workflow_version,state,draft) VALUES($1,'selection','owner','tester','/tmp','local','main','000','PROJECT_DISCOVERY',3,$2,'{}')`,[id,state]); await pool.query(`INSERT INTO intake_revisions(id,project_id,schema_version,payload,structured_sha256,markdown_sha256,artifact_uri,submitted_by) VALUES($1,$2,1,'{}',$3,$4,'file:///tmp/intake','tester')`,[revision,id,'a'.repeat(64),'b'.repeat(64)]); await pool.query(`INSERT INTO operations(id,project_id,kind,status,idempotency_key,correlation_id,revision_id,workflow_code,workflow_version) VALUES($1,$2,'PREPARE_TECHNOLOGY_SELECTION_CONTEXT','RUNNING',$3,$4,$5,'PROJECT_DISCOVERY',3)`,[operation,id,`context:${id}`,correlation,revision]); await pool.query(`INSERT INTO jobs(id,operation_id,project_id,revision_id,kind,status,idempotency_key) VALUES($1,$2,$3,$4,'PREPARE_TECHNOLOGY_SELECTION_CONTEXT','LEASED',$5)`,[job,operation,id,revision,`context:${id}`]); return { id, revision, operation, job, correlation }; };
  const cleanup=async(id:string)=>{for(const table of ['technology_inventory','technology_selection_contexts'])await pool.query(`DELETE FROM ${table} WHERE project_key=$1`,[id]);for(const table of ['events','artifacts','artifact_intents','jobs','operations','intake_revisions'])await pool.query(`DELETE FROM ${table} WHERE project_id=$1`,[id]);await pool.query(`DELETE FROM projects WHERE id=$1`,[id]);};
  const malformed=async(kind:'no-profile'|'ambiguous'|'inactive-item'|'inactive-rule')=>{const rev=randomUUID(),cat=randomUUID(),a=randomUUID(),b=randomUUID(),p1=randomUUID(),p2=randomUUID(),rule=randomUUID(),tag=randomUUID().replaceAll('-','').slice(0,12).toUpperCase(),n=Date.now()*1000+Math.floor(Math.random()*999); await pool.query(`INSERT INTO technology_categories(id,code,name,selection_mode,min_selections,max_selections,is_active,display_order) VALUES($1,$2,'test','SINGLE',1,1,true,999)`,[cat,`CTX_${tag}`]); await pool.query(`INSERT INTO technology_catalog_items(id,category_id,code,name,is_active,display_order,metadata) VALUES($1,$3,'CTX_A_${tag}','A',true,1,'{}'),($2,$3,'CTX_B_${tag}','B',true,2,'{}')`,[a,b,cat]); await pool.query(`INSERT INTO technology_profiles(id,code,name,is_active) VALUES($1,$2,'P1',true),($3,$4,'P2',true)`,[p1,`CTX_P1_${tag}`,p2,`CTX_P2_${tag}`]); await pool.query(`INSERT INTO technology_compatibility_rules(id,source_item_id,relationship_type,target_item_id,severity,message,is_active) VALUES($1,$2,'REQUIRES',$3,'ERROR','test',true)`,[rule,a,b]); await pool.query(`INSERT INTO technology_catalog_revisions(id,revision_number,status,content_hash) VALUES($1,$2,'DRAFT',$3)`,[rev,n,'f'.repeat(64)]); await pool.query(`INSERT INTO technology_catalog_revision_categories(revision_id,category_id,code,name,selection_mode,min_selections,max_selections,is_active,display_order) VALUES($1,$2,$3,'test','SINGLE',1,1,true,1)`,[rev,cat,`CTX_${tag}`]); await pool.query(`INSERT INTO technology_catalog_revision_items(revision_id,catalog_item_id,category_id,code,name,is_active,display_order,metadata) VALUES($1,$2,$4,$5,'A',$3,1,'{}'),($1,$6,$4,$7,'B',true,2,'{}')`,[rev,a,kind==='inactive-item'||kind==='inactive-rule'?false:true,cat,`CTX_A_${tag}`,b,`CTX_B_${tag}`]); if(kind!=='no-profile') { await pool.query(`INSERT INTO technology_catalog_revision_profiles(revision_id,profile_id,code,name,is_active) VALUES($1,$2,'P1','P1',true)`,[rev,p1]); if(kind==='ambiguous')await pool.query(`INSERT INTO technology_catalog_revision_profiles(revision_id,profile_id,code,name,is_active) VALUES($1,$2,'P2','P2',true)`,[rev,p2]); await pool.query(`INSERT INTO technology_catalog_revision_profile_items(revision_id,profile_id,catalog_item_id,classification,display_order) VALUES($1,$2,$3,'REQUIRED',1)`,[rev,p1,kind==='inactive-rule'?b:a]); } await pool.query(`INSERT INTO technology_catalog_revision_compatibility_rules(revision_id,compatibility_rule_id,source_item_id,relationship_type,target_item_id,severity,message,is_active) VALUES($1,$2,$3,'REQUIRES',$4,'ERROR','test',true)`,[rev,rule,a,b]); await pool.query(`UPDATE technology_catalog_revisions SET status='PUBLISHED',published_at=clock_timestamp(),published_by='test' WHERE id=$1`,[rev]); return rev;};
  test.after(async()=>pool.end());

  test('prepares an immutable published snapshot and provides the READY context consumed by F5-08', async t => {
    const catalog:any=await publish(), p=await setup(); t.after(()=>cleanup(p.id));
    const result:any=await withTransaction(c=>prepareTechnologySelectionContext(c,{id:p.job,operation_id:p.operation,project_id:p.id}));
    const context:any=(await pool.query(`SELECT * FROM technology_selection_contexts WHERE id=$1`,[result.contextId])).rows[0];
    assert.equal(context.status,'READY'); assert.equal(context.technology_catalog_revision_id,catalog.revisionId); assert.ok(context.actor); assert.equal(context.correlation_id,p.correlation);
    assert.equal((await pool.query(`SELECT state FROM projects WHERE id=$1`,[p.id])).rows[0].state,'TECHNOLOGY_BASELINE_IN_REVIEW');
    const inventory=await withTransaction(c=>startTechnologyInventory(c,p.id,`f5-09-to-f5-08:${p.id}`));
    assert.equal(inventory.status,'ACCEPTED');
    const artifact:any=(await pool.query(`SELECT storage_uri FROM artifacts WHERE project_id=$1 AND artifact_type='technology-selection-context'`,[p.id])).rows[0]; const evidence=JSON.parse(readFileSync(new URL(artifact.storage_uri),'utf8')); assert.equal(evidence.selection_context_id,context.id); assert.equal(evidence.hash,context.hash); assert.equal(evidence.actor,context.actor); assert.ok(evidence.profile_items.length>0);
    const itemId=(await pool.query(`SELECT catalog_item_id FROM technology_catalog_revision_profile_items WHERE revision_id=$1 AND profile_id=$2 LIMIT 1`,[catalog.revisionId,context.technology_profile_id])).rows[0].catalog_item_id;
    t.after(async()=>{await pool.query(`UPDATE technology_profiles SET is_active=true WHERE id=$1`,[context.technology_profile_id]);await pool.query(`UPDATE technology_catalog_items SET is_active=true WHERE id=$1`,[itemId]);});
    await pool.query(`UPDATE technology_profiles SET is_active=false WHERE id=$1`,[context.technology_profile_id]); await pool.query(`UPDATE technology_catalog_items SET is_active=false WHERE id=$1`,[itemId]);
    assert.equal((await pool.query(`SELECT technology_catalog_revision_id,technology_profile_id,hash,status FROM technology_selection_contexts WHERE id=$1`,[context.id])).rows[0].hash,context.hash);
  });

  test('rejects invalid state and leaves no partial context', async t => {
    await publish(); const p=await setup('TECHNOLOGY_BASELINE_IN_REVIEW'); t.after(()=>cleanup(p.id));
    await assert.rejects(()=>withTransaction(c=>prepareTechnologySelectionContext(c,{operation_id:p.operation,project_id:p.id})),/TECHNOLOGY_SELECTION_CONTEXT_STATE_INVALID/);
    assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM technology_selection_contexts WHERE project_key=$1`,[p.id])).rows[0].n),0);
  });

  test('rejects missing selectable publication without a partial context or evidence', async t => {
    const p=await setup(); t.after(()=>cleanup(p.id)); const client=await pool.connect();
    try { await client.query('BEGIN'); await client.query(`UPDATE technology_catalog_revisions SET status='SUPERSEDED' WHERE status='PUBLISHED'`);
      await assert.rejects(()=>prepareTechnologySelectionContext(client,{operation_id:p.operation,project_id:p.id}),/TECHNOLOGY_SELECTION_CONTEXT_PUBLISHED_REVISION_REQUIRED/);
      assert.equal(Number((await client.query(`SELECT count(*)::int n FROM technology_selection_contexts WHERE project_key=$1`,[p.id])).rows[0].n),0);
      assert.equal(Number((await client.query(`SELECT count(*)::int n FROM artifacts WHERE project_id=$1 AND artifact_type='technology-selection-context'`,[p.id])).rows[0].n),0);
      assert.equal((await client.query(`SELECT state FROM projects WHERE id=$1`,[p.id])).rows[0].state,'TECHNOLOGY_SELECTION_PREPARING');
    } finally { await client.query('ROLLBACK'); client.release(); }
  });

  for (const [kind,code] of [['no-profile','TECHNOLOGY_SELECTION_CONTEXT_PUBLISHED_REVISION_REQUIRED'],['ambiguous','TECHNOLOGY_SELECTION_CONTEXT_PROFILE_AMBIGUOUS'],['inactive-item','TECHNOLOGY_SELECTION_CONTEXT_PROFILE_ITEM_INVALID'],['inactive-rule','TECHNOLOGY_SELECTION_CONTEXT_COMPATIBILITY_RULE_INVALID']] as const) test(`fails closed for ${kind} DRAFT fixture`, async t => { const rev=await malformed(kind),p=await setup(); t.after(()=>cleanup(p.id)); t.after(()=>pool.query(`UPDATE technology_catalog_revisions SET status='SUPERSEDED' WHERE id=$1`,[rev])); const client=await pool.connect(); try { await client.query('BEGIN'); await client.query(`UPDATE technology_catalog_revisions SET status='SUPERSEDED' WHERE status='PUBLISHED' AND id<>$1`,[rev]); await assert.rejects(()=>prepareTechnologySelectionContext(client,{operation_id:p.operation,project_id:p.id}),new RegExp(code)); assert.equal(Number((await client.query(`SELECT count(*)::int n FROM technology_selection_contexts WHERE project_key=$1`,[p.id])).rows[0].n),0); assert.equal(Number((await client.query(`SELECT count(*)::int n FROM artifacts WHERE project_id=$1 AND artifact_type='technology-selection-context'`,[p.id])).rows[0].n),0); } finally { await client.query('ROLLBACK'); client.release(); } });

  test('archives a real preparing context without losing its history', async t => { const catalog:any=await publish(),p=await setup(); t.after(()=>cleanup(p.id)); const context=randomUUID(); await pool.query(`INSERT INTO technology_selection_contexts(id,project_id,project_key,technology_catalog_revision_id,hash,status) VALUES($1,$2,$3,$4,$5,'PREPARING')`,[context,p.id,p.id,catalog.revisionId,'a'.repeat(64)]); const result=await archiveProject(p.id,{confirmed:true,reason:'test'}); assert.equal(result.state,'ARCHIVED'); assert.equal((await pool.query(`SELECT status FROM technology_selection_contexts WHERE id=$1`,[context])).rows[0].status,'SUPERSEDED'); assert.equal((await pool.query(`SELECT archived_from_state FROM projects WHERE id=$1`,[p.id])).rows[0].archived_from_state,'TECHNOLOGY_SELECTION_PREPARING'); assert.equal((await pool.query(`SELECT status FROM jobs WHERE id=$1`,[p.job])).rows[0].status,'FAILED'); });

  test('rolls back after PREPARING is inserted when READY event persistence fails', async t => { await publish(); const p=await setup(); t.after(()=>cleanup(p.id)); await pool.query(`CREATE FUNCTION test_context_event_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='TECHNOLOGY_SELECTION_CONTEXT_READY' THEN RAISE EXCEPTION 'context event failure'; END IF; RETURN NEW; END $$`); await pool.query(`CREATE TRIGGER test_context_event_failure BEFORE INSERT ON events FOR EACH ROW EXECUTE FUNCTION test_context_event_failure()`); try { await assert.rejects(()=>withTransaction(c=>prepareTechnologySelectionContext(c,{operation_id:p.operation,project_id:p.id})),/context event failure/); } finally { await pool.query(`DROP TRIGGER test_context_event_failure ON events`);await pool.query(`DROP FUNCTION test_context_event_failure()`); } assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM technology_selection_contexts WHERE project_key=$1`,[p.id])).rows[0].n),0); assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM artifacts WHERE project_id=$1 AND artifact_type='technology-selection-context'`,[p.id])).rows[0].n),0); assert.equal((await pool.query(`SELECT state FROM projects WHERE id=$1`,[p.id])).rows[0].state,'TECHNOLOGY_SELECTION_PREPARING'); });

  test('prepares a context through the real worker and completes its operation', async t => { await publish(); const p=await setup(); t.after(()=>cleanup(p.id)); await pool.query(`UPDATE jobs SET status='PENDING',lease_expires_at=NULL WHERE id=$1`,[p.job]); await pool.query(`UPDATE operations SET status='QUEUED' WHERE id=$1`,[p.operation]); assert.equal(await runOnce(p.id),true); assert.equal((await pool.query(`SELECT status FROM jobs WHERE id=$1`,[p.job])).rows[0].status,'COMPLETED'); assert.equal((await pool.query(`SELECT status FROM operations WHERE id=$1`,[p.operation])).rows[0].status,'SUCCEEDED'); assert.equal((await pool.query(`SELECT state FROM projects WHERE id=$1`,[p.id])).rows[0].state,'TECHNOLOGY_BASELINE_IN_REVIEW'); assert.equal((await pool.query(`SELECT count(*)::int n FROM events WHERE project_id=$1 AND event_type='TECHNOLOGY_SELECTION_CONTEXT_READY'`,[p.id])).rows[0].n,1); });

  test('creates a new context while preserving the superseded context history', async t => { const first:any=await publish(),p=await setup();t.after(()=>cleanup(p.id));const a:any=await withTransaction(c=>prepareTechnologySelectionContext(c,{operation_id:p.operation,project_id:p.id}));const before:any=(await pool.query(`SELECT * FROM technology_selection_contexts WHERE id=$1`,[a.contextId])).rows[0];const evidenceA:any=(await pool.query(`SELECT sha256 FROM artifacts WHERE project_id=$1 AND artifact_type='technology-selection-context' ORDER BY created_at LIMIT 1`,[p.id])).rows[0];const second:any=await publish(),op=randomUUID(),job=randomUUID(),correlation=randomUUID();await pool.query(`UPDATE projects SET state='TECHNOLOGY_SELECTION_PREPARING' WHERE id=$1`,[p.id]);await pool.query(`INSERT INTO operations(id,project_id,kind,status,idempotency_key,correlation_id,workflow_code,workflow_version) VALUES($1,$2,'PREPARE_TECHNOLOGY_SELECTION_CONTEXT','RUNNING',$3,$4,'PROJECT_DISCOVERY',3)`,[op,p.id,`restart:${p.id}`,correlation]);const b:any=await withTransaction(c=>prepareTechnologySelectionContext(c,{operation_id:op,project_id:p.id,id:job}));const old:any=(await pool.query(`SELECT * FROM technology_selection_contexts WHERE id=$1`,[a.contextId])).rows[0], newest:any=(await pool.query(`SELECT * FROM technology_selection_contexts WHERE id=$1`,[b.contextId])).rows[0];assert.notEqual(a.contextId,b.contextId);assert.equal(newest.status,'READY');assert.equal(newest.technology_catalog_revision_id,second.revisionId);assert.equal(old.status,'SUPERSEDED');assert.equal(old.technology_catalog_revision_id,first.revisionId);assert.equal(old.technology_profile_id,before.technology_profile_id);assert.equal(old.hash,before.hash);assert.equal((await pool.query(`SELECT sha256 FROM artifacts WHERE project_id=$1 AND artifact_type='technology-selection-context' ORDER BY created_at LIMIT 1`,[p.id])).rows[0].sha256,evidenceA.sha256); });

  test('fails a real worker job without leaving a partial selection context', async t => { await publish();const p=await setup();t.after(()=>cleanup(p.id));await pool.query(`UPDATE jobs SET status='PENDING',attempts=99,lease_expires_at=NULL WHERE id=$1`,[p.job]);await pool.query(`UPDATE operations SET status='QUEUED' WHERE id=$1`,[p.operation]);await pool.query(`CREATE FUNCTION test_context_worker_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='TECHNOLOGY_SELECTION_CONTEXT_READY' THEN RAISE EXCEPTION 'worker context failure'; END IF; RETURN NEW; END $$`);await pool.query(`CREATE TRIGGER test_context_worker_failure BEFORE INSERT ON events FOR EACH ROW EXECUTE FUNCTION test_context_worker_failure()`);try{assert.equal(await runOnce(p.id),true);}finally{await pool.query(`DROP TRIGGER test_context_worker_failure ON events`);await pool.query(`DROP FUNCTION test_context_worker_failure()`);}const job:any=(await pool.query(`SELECT status FROM jobs WHERE id=$1`,[p.job])).rows[0];assert.notEqual(job.status,'COMPLETED');assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM technology_selection_contexts WHERE project_key=$1`,[p.id])).rows[0].n),0);assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM artifacts WHERE project_id=$1 AND artifact_type='technology-selection-context'`,[p.id])).rows[0].n),0);assert.equal((await pool.query(`SELECT state FROM projects WHERE id=$1`,[p.id])).rows[0].state,'TECHNOLOGY_SELECTION_PREPARING'); });

}
